'use client';

import { useState } from 'react';
import Link from 'next/link';

interface AIAdvisorSectionProps {
  studentProfileId: string | null;
  activeCourses: Array<{
    id: string | null;
    slug: string;
    title: string;
  }>;
}

interface Message {
  id: string;
  role: 'user' | 'assistant' | 'human';
  content: string;
  timestamp: Date;
  context?: string;
}

export function AIAdvisorSection({ studentProfileId, activeCourses }: AIAdvisorSectionProps) {
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      role: 'assistant',
      content: "Hi! I'm your AI advisor. I can help you with understanding course concepts, project guidance, job application strategies, and career path recommendations. For complex questions, I'll connect you with a human instructor.",
      timestamp: new Date(),
    },
  ]);
  const [selectedContext, setSelectedContext] = useState<'course' | 'project' | 'job' | 'general'>('general');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!message.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: message,
      timestamp: new Date(),
      context: selectedContext,
    };

    setMessages(prev => [...prev, userMessage]);
    setMessage('');
    setIsLoading(true);

    // TODO: Implement actual AI advisor API call
    // This would be context-aware based on:
    // - Current course
    // - Current project
    // - Current job application
    setTimeout(() => {
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: "I understand your question. Let me help you with that. [This is a mock response - in production, this would be generated by the AI advisor based on your context and question.]",
        timestamp: new Date(),
        context: selectedContext,
      };
      setMessages(prev => [...prev, assistantMessage]);
      setIsLoading(false);
    }, 1500);
  };

  const contextInfo = activeCourses.length > 0 
    ? `Currently learning: ${activeCourses[0].title}`
    : 'No active courses';

  const quickQuestions = {
    course: [
      'How do I get unstuck on this concept?',
      'What\'s the best way to practice this?',
      'Explain this in simpler terms',
      'What should I focus on next?',
    ],
    project: [
      'Review my project approach',
      'What technologies should I use?',
      'How do I structure this project?',
      'Best practices for this type of project',
    ],
    job: [
      'How do I tailor my application?',
      'What skills should I highlight?',
      'Career path recommendations',
      'Interview preparation tips',
    ],
    general: [
      'How do I get unstuck?',
      'What should I learn next?',
      'Review my progress',
      'Career advice',
    ],
  };

  const getContextIcon = (context: string) => {
    switch (context) {
      case 'course': return '📚';
      case 'project': return '💼';
      case 'job': return '🎯';
      default: return '💬';
    }
  };

  return (
    <section className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">AI Advisor</h2>
          <p className="text-sm text-gray-600 mt-1">AI + Human Hybrid Help</p>
        </div>
        <span className="text-xs text-gray-500 bg-blue-100 px-2 py-1 rounded">Always Available</span>
      </div>

      <div className="bg-white border border-gray-200 rounded-lg p-6">
        {/* Context Awareness */}
        <div className="mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <div className="flex items-start justify-between mb-2">
            <div className="flex-1">
              <p className="text-xs font-medium text-blue-800 mb-1">Context-Aware Assistant</p>
              <p className="text-sm text-blue-700 mb-3">{contextInfo}</p>
              {activeCourses.length > 0 && (
                <p className="text-xs text-blue-600">
                  I can help with your current course, projects, or job applications. Select a context below to get more relevant help.
                </p>
              )}
            </div>
          </div>

          {/* Context Selector */}
          <div className="flex flex-wrap gap-2 mt-3">
            {(['course', 'project', 'job', 'general'] as const).map((context) => (
              <button
                key={context}
                onClick={() => setSelectedContext(context)}
                className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                  selectedContext === context
                    ? 'bg-blue-600 text-white'
                    : 'bg-white border border-blue-200 text-blue-700 hover:bg-blue-50'
                }`}
              >
                <span className="mr-1">{getContextIcon(context)}</span>
                {context.charAt(0).toUpperCase() + context.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {/* Chat Interface */}
        <div className="space-y-4">
          <div className="h-64 overflow-y-auto border border-gray-200 rounded-lg p-4 bg-gray-50 space-y-4">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex items-start gap-3 ${
                  msg.role === 'user' ? 'flex-row-reverse' : ''
                }`}
              >
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                    msg.role === 'user'
                      ? 'bg-brand-light'
                      : msg.role === 'human'
                      ? 'bg-purple-500'
                      : 'bg-blue-500'
                  }`}
                >
                  <span className="text-white text-xs font-bold">
                    {msg.role === 'user' ? 'You' : msg.role === 'human' ? 'H' : 'AI'}
                  </span>
                </div>
                <div
                  className={`flex-1 ${
                    msg.role === 'user' ? 'text-right' : ''
                  }`}
                >
                  {msg.context && msg.context !== 'general' && (
                    <div className="flex items-center gap-1 mb-1">
                      <span className="text-xs">{getContextIcon(msg.context)}</span>
                      <span className="text-xs text-gray-500 capitalize">{msg.context}</span>
                    </div>
                  )}
                  <p className={`text-sm ${
                    msg.role === 'user' ? 'text-gray-900' : 'text-gray-700'
                  }`}>
                    {msg.content}
                  </p>
                  <p className="text-xs text-gray-400 mt-1">
                    {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </p>
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-xs font-bold">AI</span>
                </div>
                <div className="flex-1">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                </div>
              </div>
            )}
          </div>

          <form onSubmit={handleSubmit} className="flex gap-2">
            <input
              type="text"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder={`Ask a question about ${selectedContext === 'course' ? 'your course' : selectedContext === 'project' ? 'your project' : selectedContext === 'job' ? 'job applications' : 'anything'}...`}
              className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-light focus:border-transparent text-sm"
              disabled={isLoading}
            />
            <button
              type="submit"
              disabled={isLoading || !message.trim()}
              className="px-6 py-2 bg-brand-light text-white rounded-lg hover:bg-brand-light/90 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
            >
              {isLoading ? 'Sending...' : 'Send'}
            </button>
          </form>

          {/* Quick Questions */}
          <div className="pt-4 border-t border-gray-200">
            <p className="text-xs font-medium text-gray-500 mb-2">
              Quick Questions ({selectedContext}):
            </p>
            <div className="flex flex-wrap gap-2">
              {quickQuestions[selectedContext].map((question) => (
                <button
                  key={question}
                  onClick={() => setMessage(question)}
                  className="px-3 py-1.5 text-xs bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
                >
                  {question}
                </button>
              ))}
            </div>
          </div>

          {/* Help Resources */}
          <div className="pt-4 border-t border-gray-200">
            <p className="text-xs font-medium text-gray-500 mb-2">Help Resources:</p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              <Link
                href="/student/questions"
                className="px-3 py-2 text-xs bg-gray-50 border border-gray-200 rounded-lg hover:bg-gray-100 transition-colors text-center"
              >
                💬 Ask Community
              </Link>
              <Link
                href="/student/courses"
                className="px-3 py-2 text-xs bg-gray-50 border border-gray-200 rounded-lg hover:bg-gray-100 transition-colors text-center"
              >
                📚 Browse Courses
              </Link>
              <Link
                href="/student/portfolio"
                className="px-3 py-2 text-xs bg-gray-50 border border-gray-200 rounded-lg hover:bg-gray-100 transition-colors text-center"
              >
                💼 View Portfolio
              </Link>
              <button className="px-3 py-2 text-xs bg-gray-50 border border-gray-200 rounded-lg hover:bg-gray-100 transition-colors text-center">
                👤 Request Human Help
              </button>
            </div>
          </div>

          {/* AI Capabilities Info */}
          <div className="pt-4 border-t border-gray-200">
            <details className="text-xs text-gray-500">
              <summary className="cursor-pointer hover:text-gray-700">
                What can the AI Advisor help with?
              </summary>
              <div className="mt-2 p-3 bg-gray-50 rounded-lg space-y-2">
                <p className="font-medium text-gray-700">Course Help:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Explain complex concepts in simpler terms</li>
                  <li>Help you get unstuck on exercises</li>
                  <li>Suggest learning paths and next steps</li>
                  <li>Clarify course material and assignments</li>
                </ul>
                <p className="font-medium text-gray-700 mt-3">Project Guidance:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Review your project approach and architecture</li>
                  <li>Suggest technologies and best practices</li>
                  <li>Help debug and troubleshoot issues</li>
                  <li>Provide code review and optimization tips</li>
                </ul>
                <p className="font-medium text-gray-700 mt-3">Career Support:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Tailor job applications and CVs</li>
                  <li>Prepare for interviews</li>
                  <li>Career path recommendations</li>
                  <li>Skills gap analysis</li>
                </ul>
              </div>
            </details>
          </div>
        </div>
      </div>
    </section>
  );
}
