/**
 * City Banner Image Resolver
 * 
 * Maps city names (normalized keys) to banner image URLs
 * Generated from content/cities.md at build time
 */

// Import generated mapping (created at build time from content/cities.md)
// The file is generated by scripts/generate-city-banners.ts during prebuild
// It's committed to the repo to ensure Next.js can resolve it during static analysis
import { CITY_BANNER_MAP } from './cityBanners.generated';

/**
 * Default banner image URL
 * Used when city is not found in the mapping or city is null
 */
const DEFAULT_BANNER_IMAGE = 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80';

/**
 * Resolve banner image URL for a given city
 * 
 * @param city - Normalized city key (e.g., "london", "new york")
 * @returns Banner image URL (city-specific or default)
 */
export function resolveCityBanner(city: string | null | undefined): string {
  if (!city || typeof city !== 'string') {
    return DEFAULT_BANNER_IMAGE;
  }

  const normalizedCity = city.toLowerCase().trim();
  
  // Direct lookup
  if (CITY_BANNER_MAP[normalizedCity]) {
    return CITY_BANNER_MAP[normalizedCity];
  }

  // Fallback to default
  return DEFAULT_BANNER_IMAGE;
}

/**
 * Get all available cities with banner images
 * Useful for debugging or admin interfaces
 */
export function getAvailableCities(): string[] {
  return Object.keys(CITY_BANNER_MAP).sort();
}

/**
 * Check if a city has a custom banner image
 */
export function hasCityBanner(city: string | null | undefined): boolean {
  if (!city || typeof city !== 'string') {
    return false;
  }

  const normalizedCity = city.toLowerCase().trim();
  return CITY_BANNER_MAP.hasOwnProperty(normalizedCity);
}
