import { Industry } from './utils/industries';

// Course metadata for dashboard course cards
export interface CourseMetadata {
  slug: string;
  title: string;
  category: string; // Track/category (e.g., "Agentic Systems", "Vibe Engineering")
  outcome: string;
  build: string;
  bestFor: string | string[]; // Job roles - can be string or array for backward compatibility
  time: string;
  industries: Industry[]; // Array of industry domains
  isLive?: boolean; // Indicates if course is live (defaults to true if not specified)
  imageUrl?: string; // Optional direct image URL
  thumbnailUrl?: string; // Optional thumbnail image URL (camelCase)
}

export const courseMetadata: Record<string, CourseMetadata> = {
  'ai-native-software-delivery-pipelines': {
    slug: 'ai-native-software-delivery-pipelines',
    title: 'AI-Native Software Delivery Pipelines',
    category: 'Vibe Engineering',
    outcome: 'Ship AI features safely, repeatedly, and measurably.',
    build: 'A CI/CD pipeline with eval gates, prompt/version control, model routing, and rollout strategy.',
    bestFor: 'Engineers and tech leads owning reliability and release velocity.',
    time: '~4–6 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'spec-driven-development': {
    slug: 'spec-driven-development',
    title: 'Spec Driven Development',
    category: 'Vibe Engineering',
    outcome: 'Turn vague ideas into executable specs that agents and humans can deliver.',
    build: 'A spec template + workflow (requirements → acceptance tests → tasks → implementation).',
    bestFor: 'PMs, engineers, founders who want fewer misunderstandings and faster iteration.',
    time: '~3–5 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'vibe-coding-cursor-supabase': {
    slug: 'vibe-coding-cursor-supabase',
    title: 'Vibe Coding with Cursor & Supabase',
    category: 'Vibe Engineering',
    outcome: 'Build full-stack apps fast without losing structure.',
    build: 'A Supabase-backed app (auth, DB, storage, edge functions) using Cursor for iterative coding.',
    bestFor: 'Builders shipping MVPs and internal tools.',
    time: '~4–8 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'prompt-engineering': {
    slug: 'prompt-engineering',
    title: 'Prompt Engineering',
    category: 'Agentic Systems',
    outcome: 'Write prompts that are reliable, testable, and reusable.',
    build: 'A prompt library with patterns (role/task/context/output), test cases, and failure-mode checks.',
    bestFor: 'Anyone shipping LLM features into production.',
    time: '~2–4 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'agentic-rag': {
    slug: 'agentic-rag',
    title: 'Mastering Agentic RAG for Enterprise AI',
    category: 'Agentic Systems',
    outcome: 'Build self-correcting, adaptive agentic RAG systems that achieve 94.8% accuracy and strategic enterprise impact.',
    build: 'Complete agentic RAG system with CRAG, Adaptive RAG, Graph-based RAG, specialized frameworks, evaluation metrics, security, and production deployment.',
    bestFor: 'AI engineers, ML engineers, and teams building enterprise knowledge assistants with autonomous reasoning capabilities.',
    time: '~7 weeks',
    industries: ['SaaS', 'DevTools'],
  },
  'amazon-rufus-optimisation': {
    slug: 'amazon-rufus-optimisation',
    title: 'Amazon Rufus Optimisation',
    category: 'AI Search & Visibility',
    outcome: "Make your listings win in Amazon's AI shopping experiences.",
    build: 'A listing optimisation checklist + experimentation loop (titles, bullets, A+ content, Q&A signals).',
    bestFor: 'E-commerce operators and growth teams on Amazon.',
    time: '~2–4 hours',
    industries: ['E-commerce', 'Marketplaces', 'Retail / CPG'],
  },
  'reddit-ai-visibility': {
    slug: 'reddit-ai-visibility',
    title: 'Reddit AI Visibility',
    category: 'AI Search & Visibility',
    outcome: 'Earn visibility in AI-driven discovery where authenticity matters.',
    build: 'A playbook for community-first visibility (topic mapping, contribution cadence, measurement).',
    bestFor: 'Founders and marketers targeting niche audiences.',
    time: '~2–4 hours',
    industries: ['Media & Publishing', 'SaaS'],
  },
  'seo-to-aeo': {
    slug: 'seo-to-aeo',
    title: 'SEO → AEO (Search to Answer Engine Optimisation)',
    category: 'AI Search & Visibility',
    outcome: 'Rank for answers, not just clicks.',
    build: 'Content and structure patterns that improve citation/answer pickup (schema, Q&A blocks, entity coverage).',
    bestFor: 'Content, SEO, and product marketing teams.',
    time: '~3–6 hours',
    industries: ['Media & Publishing', 'SaaS', 'E-commerce'],
  },
  'hyper-personalised-marketing-advertising': {
    slug: 'hyper-personalised-marketing-advertising',
    title: 'Hyper-Personalised Marketing & Advertising',
    category: 'AI Search & Visibility',
    outcome: 'Personalise responsibly without creepy or chaotic automation.',
    build: 'A segmentation + message matrix, plus guardrails for frequency, consent, and performance.',
    bestFor: 'Performance marketers and lifecycle teams.',
    time: '~3–6 hours',
    industries: ['E-commerce', 'SaaS', 'Retail / CPG'],
  },
  'ai-visibility': {
    slug: 'ai-visibility',
    title: 'Mastering the AI Visibility Playbook',
    category: 'AI Search & Visibility',
    outcome: 'Transform from traditional SEO to AI visibility architecture and achieve 40%+ visibility increases in AI Overviews.',
    build: 'Complete AI visibility system with llms.txt, structured data, content engineering (Inverted Pyramid 2.0), entity authority, and hallucination defense.',
    bestFor: 'SEO specialists, content marketers, and technical SEOs transitioning to AI visibility optimization.',
    time: '~6–8 weeks',
    industries: ['Media & Publishing', 'SaaS', 'E-commerce'],
  },
  'decision-os-experimentation-causal-inference-uplift': {
    slug: 'decision-os-experimentation-causal-inference-uplift',
    title: 'Decision OS: Experimentation, Causal Inference & Uplift',
    category: 'AI Search & Visibility',
    outcome: 'Confidently answer "Did this change work—and should we roll it out?" by separating causation from correlation.',
    build: 'Complete Decision Operating System with experiment design, causal inference methods, result interpretation, guardrails, and rollout decision frameworks.',
    bestFor: 'Experimentation Scientists, Senior Data Scientists, Product Analysts working on A/B tests, and Growth & Personalization specialists.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Media & Publishing'],
  },
  'llm-first-websites': {
    slug: 'llm-first-websites',
    title: 'Engineering for Machine Judgment (RX)',
    category: 'AI Search & Visibility',
    outcome: 'Build LLM-first websites optimized for AI intermediaries that achieve higher visibility and citation recognition.',
    build: 'Complete RX system with ontology/taxonomy, intent-driven APIs, safety boundaries, observability, and governance frameworks.',
    bestFor: 'Web developers, product managers, and data architects building machine-first experiences.',
    time: '~6–7 weeks',
    industries: ['SaaS', 'DevTools', 'Media & Publishing'],
  },
  'paid-ai-ads-readiness': {
    slug: 'paid-ai-ads-readiness',
    title: 'Paid AI Ads Readiness',
    category: 'AI Search & Visibility',
    outcome: 'Design, simulate, and operationalise AI-native media strategies ahead of paid AI ad inventory launches.',
    build: 'Complete paid AI ads readiness plan with persona mapping, intent clusters, answer-level bidding strategy, trust signal optimization, inventory simulation, and 90-day launch playbook.',
    bestFor: 'Senior media strategists, paid media directors, agency leads, and marketing executives preparing for paid AI ad platforms.',
    time: '~6–8 weeks',
    industries: ['E-commerce', 'SaaS', 'Media & Publishing', 'Retail / CPG'],
  },
  'agentic-commerce': {
    slug: 'agentic-commerce',
    title: 'Mastering the Agentic Economy',
    category: 'Shopping & E-Commerce',
    outcome: 'Master the agentic economy from foundations to implementation, including trust-building, technical protocols, marketing strategy, and governance.',
    build: 'Complete agentic commerce implementation with ACP protocols, AEO optimization, trust frameworks, organizational design, compliance, and bias auditing.',
    bestFor: 'E-commerce leaders, product managers, marketing directors, CAOs, and strategists building agent-mediated commerce experiences.',
    time: '~7–8 weeks',
    industries: ['E-commerce', 'Marketplaces', 'Retail / CPG'],
  },
  'conversational-commerce-intelligence': {
    slug: 'conversational-commerce-intelligence',
    title: 'Conversational Commerce Intelligence Systems',
    category: 'Shopping & E-Commerce',
    outcome: 'Turn conversations into revenue intelligence.',
    build: 'An insight pipeline (intent → objections → product gaps → next best action → reporting).',
    bestFor: 'Sales, CX, and product teams.',
    time: '~4–8 hours',
    industries: ['E-commerce', 'B2B Sales / RevOps', 'SaaS'],
  },
  'ai-recommender-systems': {
    slug: 'ai-recommender-systems',
    title: 'AI Recommender Systems',
    category: 'Shopping & E-Commerce',
    outcome: 'Improve conversion with explainable recommendations.',
    build: 'A recommender blueprint (signals, ranking, exploration, evaluation, cold start handling).',
    bestFor: 'Product, data, and growth teams.',
    time: '~6–12 hours',
    industries: ['E-commerce', 'Marketplaces', 'Media & Publishing'],
  },
  '3d-for-ecommerce': {
    slug: '3d-for-ecommerce',
    title: 'Mastering 3D Commerce and Cinematic Capitalism',
    category: 'Shopping & E-Commerce',
    outcome: 'Build production-ready 3D commerce platforms that drive 2x conversion and 9% sales lift.',
    build: 'Full-stack 3D commerce platform with MERN stack, Three.js, Amazon SP-API integration, video shopping infrastructure, and enterprise scaling.',
    bestFor: 'E-commerce developers, platform architects, Amazon sellers, and product managers building immersive commerce experiences.',
    time: '~6–8 weeks',
    industries: ['E-commerce', 'Retail / CPG', 'Marketplaces'],
  },
  'ai-driven-video-synthetic-media': {
    slug: 'ai-driven-video-synthetic-media',
    title: 'AI-Driven Video & Synthetic Media',
    category: 'Media & Content Ops',
    outcome: 'Produce scalable video while keeping brand and ethics intact.',
    build: 'A production pipeline (script → storyboard → generation → edit → QC → distribution).',
    bestFor: 'Content teams and marketers.',
    time: '~3–6 hours',
    industries: ['Media & Publishing', 'E-commerce'],
  },
  'ai-content-pipelines': {
    slug: 'ai-content-pipelines',
    title: 'AI-Content Pipelines',
    category: 'Media & Content Ops',
    outcome: 'Scale content production with consistency, governance, and measurement.',
    build: 'An end-to-end pipeline (brief → research → draft → review → publish → refresh) with QA gates and attribution.',
    bestFor: 'Teams producing content weekly at volume.',
    time: '~4–10 hours',
    industries: ['Media & Publishing', 'SaaS'],
  },
  'creative-automation-templatization': {
    slug: 'creative-automation-templatization',
    title: 'Creative Automation & Templatization',
    category: 'Media & Content Ops',
    outcome: 'Scale marketing creative production while maintaining brand consistency and quality at 70-95% cost reduction.',
    build: 'Complete creative automation system with modular templates, data-driven personalization, workflow integration, quality control, and performance optimization.',
    bestFor: 'Marketing operations teams, designers, and creative operations professionals scaling creative production.',
    time: '~12 weeks',
    industries: ['Media & Publishing', 'E-commerce', 'Retail / CPG'],
  },
  'ai-governance-eu-ai-act': {
    slug: 'ai-governance-eu-ai-act',
    title: 'AI Governance & the EU AI Act',
    category: 'Trust & Regulation',
    outcome: 'Ship compliant AI systems with real operational controls.',
    build: 'A governance checklist (risk classification, documentation, human oversight, monitoring, incident response).',
    bestFor: 'Operators, compliance, product leaders in the EU orbit.',
    time: '~3–6 hours',
    industries: ['Legal & Compliance', 'SaaS', 'Finance'],
  },
  'multi-agent-systems': {
    slug: 'multi-agent-systems',
    title: 'Multi-Agent Systems',
    category: 'Agentic Systems',
    outcome: 'Deploy multi-agent AI systems at scale with production-grade infrastructure.',
    build: 'Complete multi-agent system with LangGraph, CrewAI, AutoGen, Kubernetes deployment, security, and monitoring.',
    bestFor: 'Engineers and architects building scalable agent systems.',
    time: '~12 weeks',
    industries: ['SaaS', 'DevTools'],
  },
  'problem-shooting-change-drift-failure-multi-agent-systems': {
    slug: 'problem-shooting-change-drift-failure-multi-agent-systems',
    title: 'Problem-Shooting Change, Drift, and Failure in Multi-Agent Systems',
    category: 'Agentic Systems',
    outcome: 'Design, deploy, and maintain autonomous multi-agent systems that continue to function as their environment, tools, models, and assumptions change.',
    build: 'Production-first course on failure-tolerant agent systems with drift detection, tool contracts, replay systems, cost optimization, and resumable state management.',
    bestFor: 'Engineers and architects building production-ready multi-agent systems that must handle change, drift, and failure gracefully.',
    time: '~12 weeks',
    industries: ['SaaS', 'DevTools'],
  },
  'multi-agent-sales-system': {
    slug: 'multi-agent-sales-system',
    title: 'Building the Last Sales Team You\'ll Ever Train',
    category: 'Agentic Systems',
    outcome: 'Design, orchestrate, and scale an AI-agent sales organization that eliminates hiring cycles and enables autonomous sales execution.',
    build: 'Complete autonomous sales organization with CSO agent, multichannel outreach teams, self-healing RevOps, research agents, self-updating enablement, and governance framework.',
    bestFor: 'Sales leaders done with hiring cycles, RevOps and GTM operators, founders scaling without headcount, and AI builders designing real business systems.',
    time: '~8 weeks',
    industries: ['B2B Sales / RevOps', 'SaaS'],
  },
  'building-automated-ecommerce-creative-at-scale': {
    slug: 'building-automated-ecommerce-creative-at-scale',
    title: 'Building Automated E-commerce Creative at Scale',
    category: 'Media & Content Ops',
    outcome: 'Design reusable AI creative systems, refresh entire product catalogs in hours, and generate consistent bundles, ads, and localized visuals at scale.',
    build: 'Complete automated e-commerce creative system with creative intelligence layer, art direction system, product consistency engine, bundle logic, loop automation, and distribution-ready outputs.',
    bestFor: 'E-commerce operators scaling creative production, marketing operations teams automating visual content, designers transitioning to creative systems, and brand managers maintaining consistency at scale.',
    time: '~8 weeks',
    industries: ['E-commerce', 'Retail / CPG', 'Media & Publishing'],
  },
  'ai-native-go-to-market-systems': {
    slug: 'ai-native-go-to-market-systems',
    title: 'AI-Native Go-To-Market Systems, for GTM Engineers',
    category: 'GTM & Revenue Operations',
    outcome: 'Design, build, and iterate on AI-native GTM engines that support Sales, Marketing, and CS at scale.',
    build: 'Complete AI-native GTM system with HubSpot automation, data enrichment, event-driven workflows, AI-powered classification and routing, outbound sequencing, analytics dashboards, and end-to-end monitoring.',
    bestFor: 'Early-career operators (1–4 years) in RevOps, Sales Ops, Growth Ops, Marketing Ops, or Business Systems who want to become builders of modern GTM systems.',
    time: '~8–10 weeks',
    industries: ['B2B Sales / RevOps', 'SaaS'],
    imageUrl: 'https://www.bvp.com/assets/uploads/2023/11/gtm-course-header-graphic-min.jpg',
  },
  'healthcare-agentic-ai-voice-systems': {
    slug: 'healthcare-agentic-ai-voice-systems',
    title: 'Healthcare Agentic AI & Voice Systems',
    category: 'Agentic Systems',
    outcome: 'Design, build, operate, and defend agentic and voice-based AI systems that are safe, auditable, and trusted in real hospital environments.',
    build: 'Complete production-grade healthcare AI system with safety-first architecture, clinical workflow integration, bounded autonomy agents, resilient voice pipelines, FMEA analysis, data governance, safe LLM architectures, comprehensive observability, and hospital deployment strategies.',
    bestFor: 'Senior Software Engineers, AI Engineers, or Platform Engineers working (or preparing to work) in healthcare or other safety-critical, regulated environments.',
    time: '~10–14 weeks',
    industries: ['Healthcare', 'Legal & Compliance'],
  },
  'production-ml-os': {
    slug: 'production-ml-os',
    title: 'Production ML OS: Shipping Models at Scale',
    category: 'AI Search & Visibility',
    outcome: 'Deploy, operate, and maintain ML systems that are reliable, scalable, observable, and resilient in production.',
    build: 'Complete production ML system with serving patterns, feature stores, monitoring, CI/CD, failure handling, and production readiness frameworks.',
    bestFor: 'Machine Learning Engineers, Software Engineers transitioning into ML, Senior Data Scientists moving toward production ownership, and Platform & Infrastructure engineers supporting ML.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce'],
  },
  'platform-os': {
    slug: 'platform-os',
    title: 'Platform OS: Building the Data & ML Backbone',
    category: 'AI Search & Visibility',
    outcome: 'Design, build, and evolve durable, scalable data and ML platforms that reliably support analytics, experimentation, and production AI.',
    build: 'Complete data and ML platform architecture with storage (warehouses/lakehouses), batch and streaming pipelines, feature stores, observability, governance, cost optimization, and platform operating models.',
    bestFor: 'Data Platform Engineers, ML Platform Engineers, Senior Data Engineers, and Infrastructure and Analytics Platform Leads.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce', 'B2B Sales / RevOps'],
  },
  'growth-os-data-science-revenue-scale': {
    slug: 'growth-os-data-science-revenue-scale',
    title: 'Growth OS: Data Science for Revenue & Scale',
    category: 'AI Search & Visibility',
    outcome: 'Design, evaluate, and scale data-driven growth strategies that deliver measurable revenue impact.',
    build: 'Complete Growth & Revenue Operating System with funnel diagnostics, cohort and LTV modeling, marketing mix modeling, attribution analysis, pricing optimization, experimentation frameworks, and executive communication.',
    bestFor: 'Growth Data Scientists, Marketing Data Scientists, Product Analysts focused on growth, and Analytics professionals partnering with marketing or finance.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'leadership-os-scaling-data-ai-organizations': {
    slug: 'leadership-os-scaling-data-ai-organizations',
    title: 'Leadership OS: Scaling Data & AI Organizations',
    category: 'AI Search & Visibility',
    outcome: 'Lead data and AI organizations end-to-end, aligning technology, product, and analytics with measurable business outcomes.',
    build: 'Complete Leadership & Strategy Operating System with data & AI strategy design, operating models, KPI trees and OKRs, portfolio prioritization, executive communication, and culture scaling.',
    bestFor: 'Directors and VPs of Data, Analytics, or AI, Heads of Data Science or Machine Learning, Senior Product or Engineering leaders owning AI strategy, and aspiring Chief Data or Chief AI Officers.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Finance'],
  },
  'ai-product-os': {
    slug: 'ai-product-os',
    title: 'AI Product OS: Building Intelligent User Experiences',
    category: 'AI Search & Visibility',
    outcome: 'Design and ship AI-powered product experiences that users trust, adopt, and repeatedly use.',
    build: 'Complete AI Product Operating System with opportunity discovery, UX design for AI features, decisioning and personalization systems, GenAI patterns, trust mechanisms, ethical safeguards, and measurement frameworks.',
    bestFor: 'AI Product Managers, Product Managers working with ML or GenAI, Design and UX leaders collaborating on AI products, and Senior Data Scientists transitioning into product roles.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce', 'Media & Publishing'],
  },
  'insight-os-from-raw-data-to-executive-decisions': {
    slug: 'insight-os-from-raw-data-to-executive-decisions',
    title: 'Insight OS: From Raw Data to Executive Decisions',
    category: 'AI Search & Visibility',
    outcome: 'Build an analytical foundation that transforms raw data into trusted, decision-ready insights used by product leaders, operators, and executives.',
    build: 'Complete Insight Operating System with KPI frameworks, analytical SQL, metrics layers, actionable dashboards, root-cause analysis, executive communication, and self-serve analytics enablement.',
    bestFor: 'Data Analysts, Product Analysts, Business Analysts, early-career Data Scientists, and Consultants moving into analytics roles.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'prediction-os-applied-machine-learning-for-business': {
    slug: 'prediction-os-applied-machine-learning-for-business',
    title: 'Prediction OS: Applied Machine Learning for Business',
    category: 'AI Search & Visibility',
    outcome: 'Build predictive models that are used, trusted, and embedded in real business workflows to materially influence business decisions.',
    build: 'Complete Prediction Operating System with problem framing, feature engineering at scale, predictive modeling patterns, bias evaluation, decision frameworks, productionization, and stakeholder communication.',
    bestFor: 'Data Scientists, Applied Scientists, ML-curious Analysts transitioning to DS, and Product-focused ML practitioners building business-impacting predictions.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'ai-native-product-content-engines': {
    slug: 'ai-native-product-content-engines',
    title: 'AI-Native Product Content Engines',
    category: 'AI Search & Visibility',
    outcome: 'Design, govern, and scale AI-native product content systems that improve AI recommendations, conversion, and customer trust.',
    build: 'Complete AI-native product content engine with PDP scoring, claim-proof pairing, automated generation workflows, cross-channel consistency, measurement dashboards, and organizational operating models.',
    bestFor: 'Directors of Product Content, E-commerce leaders, Product managers, Content strategists, and teams scaling product content for AI-native commerce.',
    time: '~8–10 weeks',
    industries: ['E-commerce', 'Marketplaces', 'Retail / CPG'],
  },
  'vertical-specific-ai-visibility-playbooks': {
    slug: 'vertical-specific-ai-visibility-playbooks',
    title: 'Vertical-Specific AI Visibility Playbooks',
    category: 'AI Search & Visibility',
    outcome: 'Design, defend, and operationalise proprietary AI visibility playbooks tailored to specific industries with clear competitive and risk advantage.',
    build: 'Complete vertical AI visibility program with industry-specific playbooks, risk registers, share of voice dashboards, executive briefings, and operational guidance for product, PR, and compliance teams.',
    bestFor: 'Vertical AI Strategy Directors, Industry AI Visibility Leads, Executive AI Advisors, and senior leaders building proprietary AI strategy IP.',
    time: '~8–10 weeks',
    industries: ['Finance', 'E-commerce', 'SaaS', 'Legal & Compliance'],
  },
  'ai-visibility-attribution': {
    slug: 'ai-visibility-attribution',
    title: 'AI Visibility Attribution',
    category: 'AI Search & Visibility',
    outcome: 'Design attribution systems that prove how AI-driven discovery shapes intent, drives qualified demand, and influences revenue, pipeline, and LTV.',
    build: 'Complete AI attribution system with AI-to-site attribution models, intent continuation tracking, qualified demand measurement, revenue/pipeline/LTV attribution, cost efficiency analysis, and executive reporting frameworks.',
    bestFor: 'Directors of AI Attribution & Measurement, Marketing leaders, Revenue operations professionals, and executives needing to prove AI impact on business outcomes.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Media & Publishing'],
  },
  'head-of-ai-visibility-intelligence': {
    slug: 'head-of-ai-visibility-intelligence',
    title: 'Head of AI Visibility & Intelligence',
    category: 'AI Search & Visibility',
    outcome: 'Own, measure, and operationalise brand visibility inside AI-generated answers across major LLM platforms.',
    build: 'Complete AI visibility intelligence system with platform-specific strategies, intent cluster mapping, AI answer graphs, monitoring and alerting, organizational coordination, and executive communication frameworks.',
    bestFor: 'Senior marketing leaders, Directors of AI Visibility, CMOs, and executives responsible for brand presence in AI-driven discovery.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'E-commerce', 'Media & Publishing', 'Retail / CPG'],
  },
  'underserved-persona-monetisation': {
    slug: 'underserved-persona-monetisation',
    title: 'Underserved Persona Monetisation',
    category: 'AI Search & Visibility',
    outcome: 'Identify high-intent personas surfaced by AI, design persona-aligned products and offers, and monetise them through credible positioning and AI-visible proof.',
    build: 'Complete persona monetisation system with AI-driven persona discovery, intent depth scoring, product-pricing gap analysis, persona-aligned messaging, proof collection strategies, and measurement dashboards.',
    bestFor: 'Growth leaders, Marketing directors, Product marketers, and senior marketers transitioning to AI-driven growth roles.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'ai-automation-operations': {
    slug: 'ai-automation-operations',
    title: 'AI Automation Operations',
    category: 'Agentic Systems',
    outcome: 'Design, deploy, and scale AI automation systems that deliver productivity gains while maintaining quality, trust, and organizational alignment.',
    build: 'Complete AI automation operations system with automation target selection, human-in-the-loop design, tooling integration, training and enablement, productivity measurement, and operating model frameworks.',
    bestFor: 'Operations leaders, Automation engineers, IT leaders, and professionals responsible for deploying AI automation at scale.',
    time: '~8 weeks',
    industries: ['SaaS', 'B2B Sales / RevOps', 'E-commerce'],
  },
  'building-ai-native-applications-with-weaviate': {
    slug: 'building-ai-native-applications-with-weaviate',
    title: 'Building AI-Native Applications with Weaviate',
    category: 'Agentic Systems',
    outcome: 'Build AI-native applications using Weaviate vector database, semantic search, and RAG for production-ready systems.',
    build: 'Complete AI-native application with Weaviate vector database, semantic and hybrid search, RAG pipelines, multimodal data handling, scaling and security, and production deployment.',
    bestFor: 'AI engineers, ML engineers, Backend engineers, and Data engineers building AI-native applications with vector databases.',
    time: '~8 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce'],
  },
  'lawyer-to-legal-engineer': {
    slug: 'lawyer-to-legal-engineer',
    title: 'From Lawyer to Legal Engineer',
    category: 'Trust & Regulation',
    outcome: 'Transform from practicing attorney to legal engineer, designing, governing, and deploying AI systems for legal work.',
    build: 'Complete legal AI system with legal workflow decomposition, prompt design for legal interfaces, RAG for legal knowledge, single and multi-agent systems, orchestration and state management, evaluation frameworks, and deployment strategies.',
    bestFor: 'Lawyers transitioning to legal engineering, Legal tech professionals, Legal operations directors, and professionals building AI systems for legal organizations.',
    time: '~11 weeks',
    industries: ['Legal & Compliance', 'Finance'],
  },
  'trust-os-responsible-ai-data-governance': {
    slug: 'trust-os-responsible-ai-data-governance',
    title: 'Trust OS: Responsible AI & Data Governance',
    category: 'Trust & Regulation',
    outcome: 'Design and operate AI systems that are safe, compliant, explainable, and trusted, enabling organizations to scale AI without legal, ethical, or reputational failures.',
    build: 'Complete Trust OS with responsible AI frameworks, data governance models, compliance systems, explainability mechanisms, risk assessment, and organizational governance models.',
    bestFor: 'AI governance specialists, Compliance leaders, Risk managers, Data privacy professionals, and executives responsible for AI ethics and compliance.',
    time: '~6–8 weeks',
    industries: ['Legal & Compliance', 'Finance', 'SaaS'],
  },
  'reputation-hallucination-risk-management': {
    slug: 'reputation-hallucination-risk-management',
    title: 'Reputation & Hallucination Risk Management',
    category: 'Trust & Regulation',
    outcome: 'Prevent, detect, and neutralise AI-generated brand misinformation across text, images, and summaries—before it becomes legal, regulatory, or reputational damage.',
    build: 'Complete reputation risk management system with AI hallucination taxonomy, detection mechanisms, monitoring and alerting, response protocols, brand integrity frameworks, and crisis management strategies.',
    bestFor: 'Heads of AI Brand Risk & Integrity, Reputation managers, Brand protection professionals, and executives responsible for brand safety in AI-driven environments.',
    time: '~9 weeks',
    industries: ['Media & Publishing', 'E-commerce', 'SaaS', 'Retail / CPG', 'Legal & Compliance'],
  },
  'mastering-node-based-generative-ai': {
    slug: 'mastering-node-based-generative-ai',
    title: 'Mastering Node-Based Generative AI',
    category: 'Creative AI',
    imageUrl: 'https://www.hyperakt.com/_next/image?url=https%3A%2F%2Fwww.hyperakt.com%2Fassets%2Fimages%2Fthe-nonprofit-distinction-struggle-2%2FCraft.jpg&w=3840&q=75',
    outcome: 'Master the art of node-based generative AI systems, from visual programming interfaces to production-ready creative AI applications.',
    build: 'Complete node-based generative AI system with visual programming interface, custom node creation, workflow orchestration, real-time generation, and production deployment.',
    bestFor: ['AI engineers', 'Creative technologists', 'Designers', 'Developers building creative AI tools'],
    time: '~8 weeks',
    industries: ['SaaS', 'DevTools', 'Media & Publishing'],
  },
  'economic-modeling-with-ai': {
    slug: 'economic-modeling-with-ai',
    title: 'Economic Modeling with AI',
    category: 'Economics & Maths',
    outcome: 'Build production-ready economic models using AI and machine learning to analyze market dynamics, policy impacts, and economic forecasting.',
    build: 'Complete economic modeling system with agent-based models, econometric analysis, policy simulation frameworks, market equilibrium models, and predictive analytics.',
    bestFor: ['Economists', 'Data Scientists', 'Policy Analysts', 'Financial Analysts', 'Research Economists'],
    time: '~8–10 weeks',
    industries: ['Finance', 'SaaS'],
  },
  'mathematical-foundations-for-machine-learning': {
    slug: 'mathematical-foundations-for-machine-learning',
    title: 'Mathematical Foundations for Machine Learning',
    category: 'Economics & Maths',
    outcome: 'Master the mathematical foundations essential for understanding and building machine learning systems, from linear algebra to optimization theory.',
    build: 'Complete mathematical toolkit with linear algebra applications, calculus for ML, probability and statistics, optimization methods, and numerical computing frameworks.',
    bestFor: ['Data Scientists', 'ML Engineers', 'Researchers', 'Students transitioning to ML', 'Quantitative Analysts'],
    time: '~6–8 weeks',
    industries: ['SaaS', 'DevTools', 'Finance'],
  },
  'econometrics-data-analysis': {
    slug: 'econometrics-data-analysis',
    title: 'Econometrics & Data Analysis',
    category: 'Economics & Maths',
    outcome: 'Apply econometric methods and data analysis techniques to solve real-world economic problems using modern statistical tools and AI.',
    build: 'Complete econometric analysis system with regression models, time series analysis, causal inference methods, panel data techniques, and hypothesis testing frameworks.',
    bestFor: ['Economists', 'Data Analysts', 'Research Economists', 'Policy Analysts', 'Quantitative Researchers'],
    time: '~7–9 weeks',
    industries: ['Finance', 'SaaS'],
  },
  'financial-mathematics-risk-modeling': {
    slug: 'financial-mathematics-risk-modeling',
    title: 'Financial Mathematics & Risk Modeling',
    category: 'Economics & Maths',
    outcome: 'Design and implement sophisticated financial models for pricing, risk management, and portfolio optimization using mathematical and AI techniques.',
    build: 'Complete financial modeling system with derivative pricing models, risk metrics (VaR, CVaR), portfolio optimization, stochastic processes, Monte Carlo simulation, and regulatory compliance frameworks.',
    bestFor: ['Quantitative Analysts', 'Risk Managers', 'Financial Engineers', 'Portfolio Managers', 'Traders'],
    time: '~8–10 weeks',
    industries: ['Finance'],
  },
  'economic-forecasting-with-ml': {
    slug: 'economic-forecasting-with-ml',
    title: 'Economic Forecasting with Machine Learning',
    category: 'Economics & Maths',
    outcome: 'Build accurate economic forecasting models using machine learning to predict GDP, inflation, unemployment, and other key economic indicators.',
    build: 'Complete economic forecasting system with time series models, ensemble methods, feature engineering for economic data, uncertainty quantification, and real-time forecasting pipelines.',
    bestFor: ['Economists', 'Data Scientists', 'Forecasters', 'Policy Analysts', 'Financial Analysts'],
    time: '~6–8 weeks',
    industries: ['Finance', 'SaaS'],
  },
  'mathematics-of-beauty-cosmetics': {
    slug: 'mathematics-of-beauty-cosmetics',
    title: 'The Mathematics of Beauty & Cosmetics',
    category: 'Economics & Maths',
    outcome: 'Model beauty as a measurable, optimizable system using geometry, chemistry, optics, psychology, economics, and data science to quantify aesthetic perception, optimize cosmetic formulation, and predict consumer behavior.',
    build: 'Complete mathematical beauty system with geometric and proportional models, chemical formulation optimization, psychophysical perception models, economic market analysis, data-driven personalization systems, and trend prediction models.',
    bestFor: ['Product Developers', 'Data Scientists', 'Cosmetic Chemists', 'Beauty Industry Analysts', 'R&D Engineers', 'Marketing Analysts'],
    time: '~12 weeks',
    industries: ['Retail / CPG', 'SaaS'],
  },
};

// Get category groups for organizing courses
export function getCategoryGroups(): Record<string, CourseMetadata[]> {
  const groups: Record<string, CourseMetadata[]> = {};
  
  Object.values(courseMetadata).forEach((course) => {
    if (!groups[course.category]) {
      groups[course.category] = [];
    }
    groups[course.category].push(course);
  });
  
  return groups;
}
