import { Industry } from './utils/industries';

// Course metadata for dashboard course cards
export interface CourseMetadata {
  slug: string;
  title: string;
  category: string;
  outcome: string;
  build: string;
  bestFor: string;
  time: string;
  industries: Industry[];
  imageUrl?: string; // Optional direct image URL
}

export const courseMetadata: Record<string, CourseMetadata> = {
  'ai-native-software-delivery-pipelines': {
    slug: 'ai-native-software-delivery-pipelines',
    title: 'AI-Native Software Delivery Pipelines',
    category: 'Vibe Engineering',
    outcome: 'Ship AI features safely, repeatedly, and measurably.',
    build: 'A CI/CD pipeline with eval gates, prompt/version control, model routing, and rollout strategy.',
    bestFor: 'Engineers and tech leads owning reliability and release velocity.',
    time: '~4–6 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'spec-driven-development': {
    slug: 'spec-driven-development',
    title: 'Spec Driven Development',
    category: 'Vibe Engineering',
    outcome: 'Turn vague ideas into executable specs that agents and humans can deliver.',
    build: 'A spec template + workflow (requirements → acceptance tests → tasks → implementation).',
    bestFor: 'PMs, engineers, founders who want fewer misunderstandings and faster iteration.',
    time: '~3–5 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'vibe-coding-cursor-supabase': {
    slug: 'vibe-coding-cursor-supabase',
    title: 'Vibe Coding with Cursor & Supabase',
    category: 'Vibe Engineering',
    outcome: 'Build full-stack apps fast without losing structure.',
    build: 'A Supabase-backed app (auth, DB, storage, edge functions) using Cursor for iterative coding.',
    bestFor: 'Builders shipping MVPs and internal tools.',
    time: '~4–8 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'prompt-engineering': {
    slug: 'prompt-engineering',
    title: 'Prompt Engineering',
    category: 'Agentic Systems',
    outcome: 'Write prompts that are reliable, testable, and reusable.',
    build: 'A prompt library with patterns (role/task/context/output), test cases, and failure-mode checks.',
    bestFor: 'Anyone shipping LLM features into production.',
    time: '~2–4 hours',
    industries: ['SaaS', 'DevTools'],
  },
  'agentic-rag': {
    slug: 'agentic-rag',
    title: 'Mastering Agentic RAG for Enterprise AI',
    category: 'Agentic Systems',
    outcome: 'Build self-correcting, adaptive agentic RAG systems that achieve 94.8% accuracy and strategic enterprise impact.',
    build: 'Complete agentic RAG system with CRAG, Adaptive RAG, Graph-based RAG, specialized frameworks, evaluation metrics, security, and production deployment.',
    bestFor: 'AI engineers, ML engineers, and teams building enterprise knowledge assistants with autonomous reasoning capabilities.',
    time: '~7 weeks',
    industries: ['SaaS', 'DevTools', 'Healthcare'],
  },
  'amazon-rufus-optimisation': {
    slug: 'amazon-rufus-optimisation',
    title: 'Amazon Rufus Optimisation',
    category: 'AI Search & Visibility',
    outcome: "Make your listings win in Amazon's AI shopping experiences.",
    build: 'A listing optimisation checklist + experimentation loop (titles, bullets, A+ content, Q&A signals).',
    bestFor: 'E-commerce operators and growth teams on Amazon.',
    time: '~2–4 hours',
    industries: ['E-commerce', 'Marketplaces', 'Retail / CPG'],
  },
  'reddit-ai-visibility': {
    slug: 'reddit-ai-visibility',
    title: 'Reddit AI Visibility',
    category: 'AI Search & Visibility',
    outcome: 'Earn visibility in AI-driven discovery where authenticity matters.',
    build: 'A playbook for community-first visibility (topic mapping, contribution cadence, measurement).',
    bestFor: 'Founders and marketers targeting niche audiences.',
    time: '~2–4 hours',
    industries: ['Media & Publishing', 'SaaS'],
  },
  'seo-to-aeo': {
    slug: 'seo-to-aeo',
    title: 'SEO → AEO (Search to Answer Engine Optimisation)',
    category: 'AI Search & Visibility',
    outcome: 'Rank for answers, not just clicks.',
    build: 'Content and structure patterns that improve citation/answer pickup (schema, Q&A blocks, entity coverage).',
    bestFor: 'Content, SEO, and product marketing teams.',
    time: '~3–6 hours',
    industries: ['Media & Publishing', 'SaaS', 'E-commerce'],
  },
  'hyper-personalised-marketing-advertising': {
    slug: 'hyper-personalised-marketing-advertising',
    title: 'Hyper-Personalised Marketing & Advertising',
    category: 'AI Search & Visibility',
    outcome: 'Personalise responsibly without creepy or chaotic automation.',
    build: 'A segmentation + message matrix, plus guardrails for frequency, consent, and performance.',
    bestFor: 'Performance marketers and lifecycle teams.',
    time: '~3–6 hours',
    industries: ['E-commerce', 'SaaS', 'Retail / CPG'],
  },
  'ai-visibility': {
    slug: 'ai-visibility',
    title: 'Mastering the AI Visibility Playbook',
    category: 'AI Search & Visibility',
    outcome: 'Transform from traditional SEO to AI visibility architecture and achieve 40%+ visibility increases in AI Overviews.',
    build: 'Complete AI visibility system with llms.txt, structured data, content engineering (Inverted Pyramid 2.0), entity authority, and hallucination defense.',
    bestFor: 'SEO specialists, content marketers, and technical SEOs transitioning to AI visibility optimization.',
    time: '~6–8 weeks',
    industries: ['Media & Publishing', 'SaaS', 'E-commerce'],
  },
  'decision-os-experimentation-causal-inference-uplift': {
    slug: 'decision-os-experimentation-causal-inference-uplift',
    title: 'Decision OS: Experimentation, Causal Inference & Uplift',
    category: 'AI Search & Visibility',
    outcome: 'Confidently answer "Did this change work—and should we roll it out?" by separating causation from correlation.',
    build: 'Complete Decision Operating System with experiment design, causal inference methods, result interpretation, guardrails, and rollout decision frameworks.',
    bestFor: 'Experimentation Scientists, Senior Data Scientists, Product Analysts working on A/B tests, and Growth & Personalization specialists.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Media & Publishing'],
  },
  'llm-first-websites': {
    slug: 'llm-first-websites',
    title: 'Engineering for Machine Judgment (RX)',
    category: 'AI Search & Visibility',
    outcome: 'Build LLM-first websites optimized for AI intermediaries that achieve higher visibility and citation recognition.',
    build: 'Complete RX system with ontology/taxonomy, intent-driven APIs, safety boundaries, observability, and governance frameworks.',
    bestFor: 'Web developers, product managers, and data architects building machine-first experiences.',
    time: '~6–7 weeks',
    industries: ['SaaS', 'DevTools', 'Media & Publishing'],
  },
  'paid-ai-ads-readiness': {
    slug: 'paid-ai-ads-readiness',
    title: 'Paid AI Ads Readiness',
    category: 'AI Search & Visibility',
    outcome: 'Design, simulate, and operationalise AI-native media strategies ahead of paid AI ad inventory launches.',
    build: 'Complete paid AI ads readiness plan with persona mapping, intent clusters, answer-level bidding strategy, trust signal optimization, inventory simulation, and 90-day launch playbook.',
    bestFor: 'Senior media strategists, paid media directors, agency leads, and marketing executives preparing for paid AI ad platforms.',
    time: '~6–8 weeks',
    industries: ['E-commerce', 'SaaS', 'Media & Publishing', 'Retail / CPG'],
  },
  'agentic-commerce': {
    slug: 'agentic-commerce',
    title: 'Mastering the Agentic Economy',
    category: 'Shopping & E-Commerce',
    outcome: 'Master the agentic economy from foundations to implementation, including trust-building, technical protocols, marketing strategy, and governance.',
    build: 'Complete agentic commerce implementation with ACP protocols, AEO optimization, trust frameworks, organizational design, compliance, and bias auditing.',
    bestFor: 'E-commerce leaders, product managers, marketing directors, CAOs, and strategists building agent-mediated commerce experiences.',
    time: '~7–8 weeks',
    industries: ['E-commerce', 'Marketplaces', 'Retail / CPG'],
  },
  'conversational-commerce-intelligence': {
    slug: 'conversational-commerce-intelligence',
    title: 'Conversational Commerce Intelligence Systems',
    category: 'Shopping & E-Commerce',
    outcome: 'Turn conversations into revenue intelligence.',
    build: 'An insight pipeline (intent → objections → product gaps → next best action → reporting).',
    bestFor: 'Sales, CX, and product teams.',
    time: '~4–8 hours',
    industries: ['E-commerce', 'B2B Sales / RevOps', 'SaaS'],
  },
  'ai-recommender-systems': {
    slug: 'ai-recommender-systems',
    title: 'AI Recommender Systems',
    category: 'Shopping & E-Commerce',
    outcome: 'Improve conversion with explainable recommendations.',
    build: 'A recommender blueprint (signals, ranking, exploration, evaluation, cold start handling).',
    bestFor: 'Product, data, and growth teams.',
    time: '~6–12 hours',
    industries: ['E-commerce', 'Marketplaces', 'Media & Publishing'],
  },
  '3d-for-ecommerce': {
    slug: '3d-for-ecommerce',
    title: 'Mastering 3D Commerce and Cinematic Capitalism',
    category: 'Shopping & E-Commerce',
    outcome: 'Build production-ready 3D commerce platforms that drive 2x conversion and 9% sales lift.',
    build: 'Full-stack 3D commerce platform with MERN stack, Three.js, Amazon SP-API integration, video shopping infrastructure, and enterprise scaling.',
    bestFor: 'E-commerce developers, platform architects, Amazon sellers, and product managers building immersive commerce experiences.',
    time: '~6–8 weeks',
    industries: ['E-commerce', 'Retail / CPG', 'Marketplaces'],
  },
  'ai-driven-video-synthetic-media': {
    slug: 'ai-driven-video-synthetic-media',
    title: 'AI-Driven Video & Synthetic Media',
    category: 'Media & Content Ops',
    outcome: 'Produce scalable video while keeping brand and ethics intact.',
    build: 'A production pipeline (script → storyboard → generation → edit → QC → distribution).',
    bestFor: 'Content teams and marketers.',
    time: '~3–6 hours',
    industries: ['Media & Publishing', 'E-commerce'],
  },
  'ai-content-pipelines': {
    slug: 'ai-content-pipelines',
    title: 'AI-Content Pipelines',
    category: 'Media & Content Ops',
    outcome: 'Scale content production with consistency, governance, and measurement.',
    build: 'An end-to-end pipeline (brief → research → draft → review → publish → refresh) with QA gates and attribution.',
    bestFor: 'Teams producing content weekly at volume.',
    time: '~4–10 hours',
    industries: ['Media & Publishing', 'SaaS'],
  },
  'creative-automation-templatization': {
    slug: 'creative-automation-templatization',
    title: 'Creative Automation & Templatization',
    category: 'Media & Content Ops',
    outcome: 'Scale marketing creative production while maintaining brand consistency and quality at 70-95% cost reduction.',
    build: 'Complete creative automation system with modular templates, data-driven personalization, workflow integration, quality control, and performance optimization.',
    bestFor: 'Marketing operations teams, designers, and creative operations professionals scaling creative production.',
    time: '~12 weeks',
    industries: ['Media & Publishing', 'E-commerce', 'Retail / CPG'],
  },
  'ai-governance-eu-ai-act': {
    slug: 'ai-governance-eu-ai-act',
    title: 'AI Governance & the EU AI Act',
    category: 'Trust & Regulation',
    outcome: 'Ship compliant AI systems with real operational controls.',
    build: 'A governance checklist (risk classification, documentation, human oversight, monitoring, incident response).',
    bestFor: 'Operators, compliance, product leaders in the EU orbit.',
    time: '~3–6 hours',
    industries: ['Legal & Compliance', 'SaaS', 'Healthcare', 'Fintech'],
  },
  'multi-agent-systems': {
    slug: 'multi-agent-systems',
    title: 'Multi-Agent Systems',
    category: 'Agentic Systems',
    outcome: 'Deploy multi-agent AI systems at scale with production-grade infrastructure.',
    build: 'Complete multi-agent system with LangGraph, CrewAI, AutoGen, Kubernetes deployment, security, and monitoring.',
    bestFor: 'Engineers and architects building scalable agent systems.',
    time: '~12 weeks',
    industries: ['SaaS', 'DevTools'],
  },
  'problem-shooting-change-drift-failure-multi-agent-systems': {
    slug: 'problem-shooting-change-drift-failure-multi-agent-systems',
    title: 'Problem-Shooting Change, Drift, and Failure in Multi-Agent Systems',
    category: 'Agentic Systems',
    outcome: 'Design, deploy, and maintain autonomous multi-agent systems that continue to function as their environment, tools, models, and assumptions change.',
    build: 'Production-first course on failure-tolerant agent systems with drift detection, tool contracts, replay systems, cost optimization, and resumable state management.',
    bestFor: 'Engineers and architects building production-ready multi-agent systems that must handle change, drift, and failure gracefully.',
    time: '~12 weeks',
    industries: ['SaaS', 'DevTools'],
  },
  'multi-agent-sales-system': {
    slug: 'multi-agent-sales-system',
    title: 'Building the Last Sales Team You\'ll Ever Train',
    category: 'Agentic Systems',
    outcome: 'Design, orchestrate, and scale an AI-agent sales organization that eliminates hiring cycles and enables autonomous sales execution.',
    build: 'Complete autonomous sales organization with CSO agent, multichannel outreach teams, self-healing RevOps, research agents, self-updating enablement, and governance framework.',
    bestFor: 'Sales leaders done with hiring cycles, RevOps and GTM operators, founders scaling without headcount, and AI builders designing real business systems.',
    time: '~8 weeks',
    industries: ['B2B Sales / RevOps', 'SaaS'],
  },
  'building-automated-ecommerce-creative-at-scale': {
    slug: 'building-automated-ecommerce-creative-at-scale',
    title: 'Building Automated E-commerce Creative at Scale',
    category: 'Media & Content Ops',
    outcome: 'Design reusable AI creative systems, refresh entire product catalogs in hours, and generate consistent bundles, ads, and localized visuals at scale.',
    build: 'Complete automated e-commerce creative system with creative intelligence layer, art direction system, product consistency engine, bundle logic, loop automation, and distribution-ready outputs.',
    bestFor: 'E-commerce operators scaling creative production, marketing operations teams automating visual content, designers transitioning to creative systems, and brand managers maintaining consistency at scale.',
    time: '~8 weeks',
    industries: ['E-commerce', 'Retail / CPG', 'Media & Publishing'],
  },
  'ai-native-go-to-market-systems': {
    slug: 'ai-native-go-to-market-systems',
    title: 'AI-Native Go-To-Market Systems, for GTM Engineers',
    category: 'GTM & Revenue Operations',
    outcome: 'Design, build, and iterate on AI-native GTM engines that support Sales, Marketing, and CS at scale.',
    build: 'Complete AI-native GTM system with HubSpot automation, data enrichment, event-driven workflows, AI-powered classification and routing, outbound sequencing, analytics dashboards, and end-to-end monitoring.',
    bestFor: 'Early-career operators (1–4 years) in RevOps, Sales Ops, Growth Ops, Marketing Ops, or Business Systems who want to become builders of modern GTM systems.',
    time: '~8–10 weeks',
    industries: ['B2B Sales / RevOps', 'SaaS'],
  },
  'healthcare-agentic-ai-voice-systems': {
    slug: 'healthcare-agentic-ai-voice-systems',
    title: 'Healthcare Agentic AI & Voice Systems',
    category: 'Agentic Systems',
    outcome: 'Design, build, operate, and defend agentic and voice-based AI systems that are safe, auditable, and trusted in real hospital environments.',
    build: 'Complete production-grade healthcare AI system with safety-first architecture, clinical workflow integration, bounded autonomy agents, resilient voice pipelines, FMEA analysis, data governance, safe LLM architectures, comprehensive observability, and hospital deployment strategies.',
    bestFor: 'Senior Software Engineers, AI Engineers, or Platform Engineers working (or preparing to work) in healthcare or other safety-critical, regulated environments.',
    time: '~10–14 weeks',
    industries: ['Healthcare', 'Legal & Compliance'],
  },
  'production-ml-os': {
    slug: 'production-ml-os',
    title: 'Production ML OS: Shipping Models at Scale',
    category: 'AI Search & Visibility',
    outcome: 'Deploy, operate, and maintain ML systems that are reliable, scalable, observable, and resilient in production.',
    build: 'Complete production ML system with serving patterns, feature stores, monitoring, CI/CD, failure handling, and production readiness frameworks.',
    bestFor: 'Machine Learning Engineers, Software Engineers transitioning into ML, Senior Data Scientists moving toward production ownership, and Platform & Infrastructure engineers supporting ML.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce'],
  },
  'platform-os': {
    slug: 'platform-os',
    title: 'Platform OS: Building the Data & ML Backbone',
    category: 'AI Search & Visibility',
    outcome: 'Design, build, and evolve durable, scalable data and ML platforms that reliably support analytics, experimentation, and production AI.',
    build: 'Complete data and ML platform architecture with storage (warehouses/lakehouses), batch and streaming pipelines, feature stores, observability, governance, cost optimization, and platform operating models.',
    bestFor: 'Data Platform Engineers, ML Platform Engineers, Senior Data Engineers, and Infrastructure and Analytics Platform Leads.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce', 'B2B Sales / RevOps'],
  },
  'growth-os-data-science-revenue-scale': {
    slug: 'growth-os-data-science-revenue-scale',
    title: 'Growth OS: Data Science for Revenue & Scale',
    category: 'AI Search & Visibility',
    outcome: 'Design, evaluate, and scale data-driven growth strategies that deliver measurable revenue impact.',
    build: 'Complete Growth & Revenue Operating System with funnel diagnostics, cohort and LTV modeling, marketing mix modeling, attribution analysis, pricing optimization, experimentation frameworks, and executive communication.',
    bestFor: 'Growth Data Scientists, Marketing Data Scientists, Product Analysts focused on growth, and Analytics professionals partnering with marketing or finance.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'leadership-os-scaling-data-ai-organizations': {
    slug: 'leadership-os-scaling-data-ai-organizations',
    title: 'Leadership OS: Scaling Data & AI Organizations',
    category: 'AI Search & Visibility',
    outcome: 'Lead data and AI organizations end-to-end, aligning technology, product, and analytics with measurable business outcomes.',
    build: 'Complete Leadership & Strategy Operating System with data & AI strategy design, operating models, KPI trees and OKRs, portfolio prioritization, executive communication, and culture scaling.',
    bestFor: 'Directors and VPs of Data, Analytics, or AI, Heads of Data Science or Machine Learning, Senior Product or Engineering leaders owning AI strategy, and aspiring Chief Data or Chief AI Officers.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Healthcare', 'Fintech'],
  },
  'ai-product-os': {
    slug: 'ai-product-os',
    title: 'AI Product OS: Building Intelligent User Experiences',
    category: 'AI Search & Visibility',
    outcome: 'Design and ship AI-powered product experiences that users trust, adopt, and repeatedly use.',
    build: 'Complete AI Product Operating System with opportunity discovery, UX design for AI features, decisioning and personalization systems, GenAI patterns, trust mechanisms, ethical safeguards, and measurement frameworks.',
    bestFor: 'AI Product Managers, Product Managers working with ML or GenAI, Design and UX leaders collaborating on AI products, and Senior Data Scientists transitioning into product roles.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'DevTools', 'E-commerce', 'Media & Publishing'],
  },
  'insight-os-from-raw-data-to-executive-decisions': {
    slug: 'insight-os-from-raw-data-to-executive-decisions',
    title: 'Insight OS: From Raw Data to Executive Decisions',
    category: 'AI Search & Visibility',
    outcome: 'Build an analytical foundation that transforms raw data into trusted, decision-ready insights used by product leaders, operators, and executives.',
    build: 'Complete Insight Operating System with KPI frameworks, analytical SQL, metrics layers, actionable dashboards, root-cause analysis, executive communication, and self-serve analytics enablement.',
    bestFor: 'Data Analysts, Product Analysts, Business Analysts, early-career Data Scientists, and Consultants moving into analytics roles.',
    time: '~6–8 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
  'prediction-os-applied-machine-learning-for-business': {
    slug: 'prediction-os-applied-machine-learning-for-business',
    title: 'Prediction OS: Applied Machine Learning for Business',
    category: 'AI Search & Visibility',
    outcome: 'Build predictive models that are used, trusted, and embedded in real business workflows to materially influence business decisions.',
    build: 'Complete Prediction Operating System with problem framing, feature engineering at scale, predictive modeling patterns, bias evaluation, decision frameworks, productionization, and stakeholder communication.',
    bestFor: 'Data Scientists, Applied Scientists, ML-curious Analysts transitioning to DS, and Product-focused ML practitioners building business-impacting predictions.',
    time: '~8–10 weeks',
    industries: ['SaaS', 'E-commerce', 'B2B Sales / RevOps', 'Retail / CPG'],
  },
};

// Get category groups for organizing courses
export function getCategoryGroups(): Record<string, CourseMetadata[]> {
  const groups: Record<string, CourseMetadata[]> = {};
  
  Object.values(courseMetadata).forEach((course) => {
    if (!groups[course.category]) {
      groups[course.category] = [];
    }
    groups[course.category].push(course);
  });
  
  return groups;
}
