-- Seed jobs and offers: sample job listings and tool discounts
-- No dependencies - can be seeded independently
-- Uses hardcoded UUIDs for easy reference and consistency
--
-- NOTE: This script should be run using a direct database connection (psql)
-- which bypasses Row Level Security (RLS). The connection string should be
-- the "Direct connection" or "Transaction pooler" from Supabase Dashboard.

BEGIN;

-- Insert sample jobs with hardcoded deterministic UUIDs
INSERT INTO jobs (
  id, title, company, description, job_type, experience_level, location, is_remote,
  salary_range, status, matching_score, skills, skills_missing, recommended_for_courses, 
  external_url, is_active, is_featured
)
VALUES
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc01'::uuid,
    'AI Engineer - Multi-Agent Systems',
    'TechCorp AI',
    'We are looking for an AI Engineer to build and deploy production-ready multi-agent systems. You will work with LangGraph, CrewAI, and Kubernetes to scale agent infrastructure.',
    'full_time',
    'mid',
    'San Francisco, CA',
    true,
    '$150k - $200k',
    'recommended',
    85,
    ARRAY['Python', 'LangGraph', 'CrewAI', 'Kubernetes', 'PostgreSQL', 'AI/ML'],
    ARRAY[]::TEXT[],
    ARRAY['multi-agent-systems', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/ai-engineer-multi-agent',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc02'::uuid,
    'Full-Stack Developer - AI-Native Applications',
    'StartupXYZ',
    'Join our team building AI-native applications using Cursor, Supabase, and modern web technologies. You will work on fast-moving projects with iterative development.',
    'full_time',
    'entry',
    'Remote',
    true,
    '$100k - $130k',
    'recommended',
    75,
    ARRAY['TypeScript', 'Next.js', 'Supabase', 'PostgreSQL', 'React'],
    ARRAY[]::TEXT[],
    ARRAY['vibe-coding-cursor-supabase', 'ai-native-software-delivery-pipelines'],
    'https://example.com/jobs/fullstack-ai-native',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc03'::uuid,
    'Senior AI Visibility Specialist',
    'Digital Marketing Agency',
    'Lead AI visibility optimization for enterprise clients. You will implement llms.txt, structured data, and content engineering strategies to improve AI Overview visibility.',
    'full_time',
    'senior',
    'New York, NY',
    false,
    '$120k - $160k',
    'recommended',
    90,
    ARRAY['SEO', 'AI Visibility', 'Content Strategy', 'Structured Data', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['ai-visibility', 'seo-to-aeo', 'llm-first-websites'],
    'https://example.com/jobs/ai-visibility-specialist',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc04'::uuid,
    'E-commerce AI Engineer',
    'EcomTech Solutions',
    'Build AI-driven e-commerce features including recommender systems, conversational commerce, and 3D product experiences.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$130k - $170k',
    'recommended',
    80,
    ARRAY['Python', 'Machine Learning', 'E-commerce', 'Recommendation Systems', 'Three.js'],
    ARRAY[]::TEXT[],
    ARRAY['ai-recommender-systems', 'agentic-commerce', '3d-for-ecommerce'],
    'https://example.com/jobs/ecommerce-ai-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc05'::uuid,
    'AI Governance Consultant',
    'ComplianceTech',
    'Help clients navigate EU AI Act compliance and implement governance frameworks for AI systems.',
    'contract',
    'senior',
    'Remote',
    true,
    '$150/hour',
    'recommended',
    70,
    ARRAY['AI Governance', 'EU AI Act', 'Compliance', 'Risk Assessment', 'Documentation'],
    ARRAY[]::TEXT[],
    ARRAY['ai-governance-eu-ai-act'],
    'https://example.com/jobs/ai-governance-consultant',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc06'::uuid,
    'Stretch Role: Lead AI Architect',
    'Enterprise AI Corp',
    'Lead architecture for enterprise AI systems. Requires deep experience with multi-agent systems, RAG, and production deployment.',
    'full_time',
    'lead',
    'Remote',
    true,
    '$200k - $250k',
    'stretch',
    60,
    ARRAY['Multi-Agent Systems', 'RAG', 'Kubernetes', 'MLOps', 'System Design'],
    ARRAY['Enterprise Architecture', 'Team Leadership'],
    ARRAY['multi-agent-systems', 'agentic-rag', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/lead-ai-architect',
    true,
    false
  ),
  -- Entry Level Jobs
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc07'::uuid,
    'Junior Prompt Engineer',
    'AI Startup Labs',
    'Help design and test prompts for AI applications. Work with the team to build reliable, testable prompt libraries.',
    'full_time',
    'entry',
    'Remote',
    true,
    '$80k - $100k',
    'recommended',
    78,
    ARRAY['Prompt Engineering', 'Python', 'Testing', 'Documentation'],
    ARRAY[]::TEXT[],
    ARRAY['prompt-engineering', 'spec-driven-development'],
    'https://example.com/jobs/junior-prompt-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc08'::uuid,
    'AI Content Intern',
    'MediaFlow',
    'Summer internship working on AI-driven content pipelines. Learn content production workflows and AI tools.',
    'internship',
    'entry',
    'New York, NY',
    false,
    '$25/hour',
    'new',
    65,
    ARRAY['Content Writing', 'AI Tools', 'Content Strategy'],
    ARRAY[]::TEXT[],
    ARRAY['ai-content-pipelines', 'ai-driven-video-synthetic-media'],
    'https://example.com/jobs/ai-content-intern',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc09'::uuid,
    'Frontend Developer - LLM-First Websites',
    'WebTech Innovations',
    'Build LLM-first websites optimized for AI intermediaries. Work with structured data, APIs, and semantic HTML.',
    'full_time',
    'entry',
    'Remote',
    true,
    '$90k - $110k',
    'unlocked',
    72,
    ARRAY['HTML', 'CSS', 'JavaScript', 'Structured Data', 'SEO'],
    ARRAY[]::TEXT[],
    ARRAY['llm-first-websites', 'seo-to-aeo'],
    'https://example.com/jobs/frontend-llm-first',
    true,
    false
  ),
  -- Mid Level Jobs
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc10'::uuid,
    'RAG Systems Engineer',
    'DataIntelligence Co',
    'Build and deploy production RAG systems with self-correction and adaptive retrieval. Work with vector databases and LLMs.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$140k - $180k',
    'recommended',
    88,
    ARRAY['Python', 'RAG', 'Vector Databases', 'LLMs', 'LangChain'],
    ARRAY[]::TEXT[],
    ARRAY['agentic-rag', 'multi-agent-systems'],
    'https://example.com/jobs/rag-systems-engineer',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc11'::uuid,
    'E-commerce AI Product Manager',
    'ShopSmart AI',
    'Lead product strategy for AI-powered e-commerce features. Drive recommender systems, conversational commerce, and personalization.',
    'full_time',
    'mid',
    'San Francisco, CA',
    true,
    '$130k - $160k',
    'recommended',
    82,
    ARRAY['Product Management', 'E-commerce', 'AI/ML', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['agentic-commerce', 'ai-recommender-systems', 'conversational-commerce-intelligence'],
    'https://example.com/jobs/ecommerce-ai-pm',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc12'::uuid,
    '3D Commerce Developer',
    'RetailTech Solutions',
    'Build 3D product experiences for e-commerce. Work with Three.js, WebGL, and 3D asset pipelines.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$125k - $155k',
    'recommended',
    75,
    ARRAY['Three.js', 'WebGL', 'JavaScript', '3D Modeling', 'E-commerce'],
    ARRAY[]::TEXT[],
    ARRAY['3d-for-ecommerce', 'agentic-commerce'],
    'https://example.com/jobs/3d-commerce-developer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc13'::uuid,
    'AI DevOps Engineer',
    'CloudScale AI',
    'Build CI/CD pipelines for AI features with eval gates, prompt versioning, and model routing. Deploy AI systems at scale.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$135k - $170k',
    'recommended',
    80,
    ARRAY['CI/CD', 'Kubernetes', 'Python', 'MLOps', 'Monitoring'],
    ARRAY[]::TEXT[],
    ARRAY['ai-native-software-delivery-pipelines', 'multi-agent-systems'],
    'https://example.com/jobs/ai-devops-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc14'::uuid,
    'SEO to AEO Specialist',
    'SearchOptimize Agency',
    'Transform traditional SEO strategies into Answer Engine Optimization. Build content patterns for AI Overview visibility.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$110k - $140k',
    'unlocked',
    70,
    ARRAY['SEO', 'Content Strategy', 'Structured Data', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['seo-to-aeo', 'ai-visibility'],
    'https://example.com/jobs/seo-aeo-specialist',
    true,
    false
  ),
  -- Senior Level Jobs
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc15'::uuid,
    'Senior Multi-Agent Systems Architect',
    'Enterprise AI Solutions',
    'Design and deploy production multi-agent systems with fault tolerance, drift detection, and state management.',
    'full_time',
    'senior',
    'Remote',
    true,
    '$180k - $220k',
    'recommended',
    92,
    ARRAY['Multi-Agent Systems', 'LangGraph', 'Kubernetes', 'System Design', 'Observability'],
    ARRAY[]::TEXT[],
    ARRAY['multi-agent-systems', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/senior-multi-agent-architect',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc16'::uuid,
    'Head of AI Visibility',
    'Digital Marketing Leaders',
    'Lead AI visibility strategy for enterprise clients. Build teams and implement comprehensive AI Overview optimization programs.',
    'full_time',
    'senior',
    'New York, NY',
    false,
    '$160k - $200k',
    'recommended',
    90,
    ARRAY['AI Visibility', 'SEO', 'Content Strategy', 'Team Leadership', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['ai-visibility', 'llm-first-websites', 'seo-to-aeo'],
    'https://example.com/jobs/head-ai-visibility',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc17'::uuid,
    'Senior Conversational Commerce Engineer',
    'EcomAI Platform',
    'Build intelligent conversational commerce systems. Implement intent detection, objection handling, and revenue intelligence pipelines.',
    'full_time',
    'senior',
    'Remote',
    true,
    '$155k - $190k',
    'recommended',
    85,
    ARRAY['Python', 'NLP', 'E-commerce', 'Conversational AI', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['conversational-commerce-intelligence', 'agentic-commerce'],
    'https://example.com/jobs/senior-conversational-commerce',
    true,
    false
  ),
  -- Contract & Freelance Jobs
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc18'::uuid,
    'Freelance Prompt Engineer',
    'AI Consulting Collective',
    'Contract work building prompt libraries and testing frameworks for various clients. Flexible hours, remote work.',
    'freelance',
    'mid',
    'Remote',
    true,
    '$80/hour',
    'unlocked',
    68,
    ARRAY['Prompt Engineering', 'Python', 'Testing', 'Documentation'],
    ARRAY[]::TEXT[],
    ARRAY['prompt-engineering', 'spec-driven-development'],
    'https://example.com/jobs/freelance-prompt-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc19'::uuid,
    'Part-Time AI Content Strategist',
    'ContentAI Studio',
    'Part-time role helping clients build AI content pipelines. Work on content strategy, production workflows, and quality gates.',
    'part_time',
    'mid',
    'Remote',
    true,
    '$60/hour',
    'new',
    65,
    ARRAY['Content Strategy', 'AI Tools', 'Content Production', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['ai-content-pipelines', 'ai-driven-video-synthetic-media'],
    'https://example.com/jobs/parttime-content-strategist',
    true,
    false
  ),
  -- Locked Jobs (require additional skills)
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc20'::uuid,
    'Locked: Senior Recommender Systems Engineer',
    'PersonalizationAI',
    'Build production recommender systems with explainability and cold start handling. Requires deep ML experience.',
    'full_time',
    'senior',
    'Remote',
    true,
    '$170k - $210k',
    'locked',
    55,
    ARRAY['Machine Learning', 'Recommender Systems', 'Python', 'TensorFlow'],
    ARRAY['Deep Learning', 'Production ML Systems'],
    ARRAY['ai-recommender-systems', 'multi-agent-systems'],
    'https://example.com/jobs/senior-recommender-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc21'::uuid,
    'Locked: AI Video Production Lead',
    'MediaTech Studios',
    'Lead AI-driven video production pipelines. Requires experience with video generation, editing, and distribution.',
    'full_time',
    'senior',
    'Los Angeles, CA',
    false,
    '$150k - $180k',
    'locked',
    50,
    ARRAY['Video Production', 'AI Tools', 'Content Strategy'],
    ARRAY['Video Editing', 'Production Workflows'],
    ARRAY['ai-driven-video-synthetic-media', 'ai-content-pipelines'],
    'https://example.com/jobs/ai-video-production-lead',
    true,
    false
  ),
  -- Stretch Roles
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc22'::uuid,
    'Stretch: VP of AI Engineering',
    'TechCorp Global',
    'Lead AI engineering organization. Requires extensive experience with multi-agent systems, RAG, and enterprise AI deployment.',
    'full_time',
    'executive',
    'San Francisco, CA',
    true,
    '$250k - $350k',
    'stretch',
    45,
    ARRAY['Multi-Agent Systems', 'RAG', 'Enterprise Architecture', 'Team Leadership'],
    ARRAY['Executive Leadership', 'Organizational Design', 'Strategic Planning'],
    ARRAY['multi-agent-systems', 'agentic-rag', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/vp-ai-engineering',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc23'::uuid,
    'Stretch: Chief AI Officer',
    'Innovation Labs',
    'Executive role leading AI strategy and implementation across the organization. Requires deep technical and business expertise.',
    'full_time',
    'executive',
    'Remote',
    true,
    '$300k - $400k',
    'stretch',
    40,
    ARRAY['AI Strategy', 'Business Leadership', 'Technical Architecture'],
    ARRAY['Executive Experience', 'Board-Level Strategy', 'Industry Relationships'],
    ARRAY['multi-agent-systems', 'agentic-rag', 'ai-governance-eu-ai-act'],
    'https://example.com/jobs/chief-ai-officer',
    true,
    false
  ),
  -- Additional Recommended Jobs
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc24'::uuid,
    'Hyper-Personalization Engineer',
    'MarketingAI Co',
    'Build hyper-personalized marketing systems with responsible automation. Implement segmentation, message matrices, and consent frameworks.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$120k - $150k',
    'recommended',
    77,
    ARRAY['Marketing Automation', 'Personalization', 'Analytics', 'Python'],
    ARRAY[]::TEXT[],
    ARRAY['hyper-personalised-marketing-advertising', 'ai-recommender-systems'],
    'https://example.com/jobs/hyper-personalization-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc25'::uuid,
    'Amazon Rufus Optimization Specialist',
    'E-commerce Growth Agency',
    'Optimize product listings for Amazon''s AI shopping experiences. Build experimentation loops and measurement frameworks.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$100k - $130k',
    'unlocked',
    73,
    ARRAY['E-commerce', 'Amazon', 'SEO', 'Content Optimization', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['amazon-rufus-optimisation', 'seo-to-aeo'],
    'https://example.com/jobs/amazon-rufus-specialist',
    true,
    false
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  company = EXCLUDED.company,
  description = EXCLUDED.description,
  job_type = EXCLUDED.job_type,
  experience_level = EXCLUDED.experience_level,
  location = EXCLUDED.location,
  is_remote = EXCLUDED.is_remote,
  salary_range = EXCLUDED.salary_range,
  status = EXCLUDED.status,
  matching_score = EXCLUDED.matching_score,
  skills = EXCLUDED.skills,
  skills_missing = EXCLUDED.skills_missing,
  recommended_for_courses = EXCLUDED.recommended_for_courses,
  external_url = EXCLUDED.external_url,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = NOW();

-- Insert sample offers with hardcoded deterministic UUIDs
INSERT INTO offers (
  id, title, provider, description, category, discount_text, discount_type, discount_value,
  discount_code, external_url, eligibility, recommended_for_courses, original_price,
  discounted_price, features, is_active, is_recommended, expiration_date, max_usage
)
VALUES
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc01'::uuid,
    'Supabase Pro - 50% off first 3 months',
    'Supabase',
    'Get 50% off Supabase Pro plan for the first 3 months. Perfect for building full-stack apps with auth, database, and storage.',
    'database',
    '50% off first 3 months',
    'percentage',
    50.00,
    'STUDENT50',
    'https://supabase.com/pricing',
    'New users only',
    ARRAY['vibe-coding-cursor-supabase', 'ai-native-software-delivery-pipelines'],
    '$25/month',
    '$12.50/month (first 3 months)',
    ARRAY['Unlimited API requests', '500GB database space', '50GB file storage', 'Priority support'],
    true,
    true,
    NOW() + INTERVAL '90 days',
    100
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc02'::uuid,
    'OpenAI API Credits - $100 free',
    'OpenAI',
    'Get $100 in free OpenAI API credits to build AI features. Perfect for experimenting with GPT-4, Whisper, and DALL-E.',
    'ai_llm',
    '$100 free credits',
    'free_credits',
    100.00,
    'STUDENT100',
    'https://platform.openai.com/signup',
    'New users only, requires student email',
    ARRAY['prompt-engineering', 'agentic-rag', 'multi-agent-systems'],
    '$0.01/1K tokens',
    '$100 free',
    ARRAY['Access to GPT-4', 'Whisper API', 'DALL-E API', 'Embeddings API'],
    true,
    true,
    NOW() + INTERVAL '60 days',
    50
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc03'::uuid,
    'Vercel Pro - Extended Trial',
    'Vercel',
    'Get 30 days free trial of Vercel Pro (normally 14 days). Deploy Next.js apps with zero configuration.',
    'hosting',
    '30 days free trial',
    'extended_trial',
    NULL,
    NULL,
    'New users only',
    ARRAY['vibe-coding-cursor-supabase', 'llm-first-websites'],
    '$20/month',
    'Free for 30 days',
    ARRAY['Unlimited deployments', '100GB bandwidth', 'Team collaboration', 'Analytics'],
    true,
    false,
    NOW() + INTERVAL '120 days',
    NULL
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc04'::uuid,
    'Pinecone Starter - 20% off',
    'Pinecone',
    'Get 20% off Pinecone Starter plan for vector database needs. Perfect for RAG applications.',
    'vector_database',
    '20% off first year',
    'percentage',
    20.00,
    'RAG20',
    'https://www.pinecone.io/pricing',
    'New users only',
    ARRAY['agentic-rag', 'multi-agent-systems'],
    '$70/month',
    '$56/month (first year)',
    ARRAY['1M vectors', '5GB storage', 'Basic support'],
    true,
    true,
    NOW() + INTERVAL '180 days',
    200
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc05'::uuid,
    'LangSmith Monitoring - Free Tier Upgrade',
    'LangChain',
    'Upgrade to LangSmith Pro features for free. Monitor and debug LangGraph applications.',
    'observability',
    'Free Pro tier upgrade',
    'tier_upgrade',
    NULL,
    NULL,
    'Students only',
    ARRAY['multi-agent-systems', 'agentic-rag'],
    '$99/month',
    'Free',
    ARRAY['Advanced tracing', 'Team collaboration', 'Custom dashboards', 'Priority support'],
    true,
    false,
    NOW() + INTERVAL '90 days',
    50
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  discount_text = EXCLUDED.discount_text,
  discount_type = EXCLUDED.discount_type,
  discount_value = EXCLUDED.discount_value,
  discount_code = EXCLUDED.discount_code,
  external_url = EXCLUDED.external_url,
  eligibility = EXCLUDED.eligibility,
  recommended_for_courses = EXCLUDED.recommended_for_courses,
  original_price = EXCLUDED.original_price,
  discounted_price = EXCLUDED.discounted_price,
  features = EXCLUDED.features,
  is_active = EXCLUDED.is_active,
  is_recommended = EXCLUDED.is_recommended,
  expiration_date = EXCLUDED.expiration_date,
  max_usage = EXCLUDED.max_usage,
  updated_at = NOW();

COMMIT;
