-- Seed jobs and offers: sample job listings and tool discounts
-- No dependencies - can be seeded independently
-- Uses hardcoded UUIDs for easy reference and consistency

BEGIN;

-- Insert sample jobs with hardcoded deterministic UUIDs
INSERT INTO jobs (
  id, title, company, description, job_type, experience_level, location, is_remote,
  salary_range, status, matching_score, skills, skills_missing, recommended_for_courses, 
  external_url, is_active, is_featured
)
VALUES
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc01'::uuid,
    'AI Engineer - Multi-Agent Systems',
    'TechCorp AI',
    'We are looking for an AI Engineer to build and deploy production-ready multi-agent systems. You will work with LangGraph, CrewAI, and Kubernetes to scale agent infrastructure.',
    'full_time',
    'mid',
    'San Francisco, CA',
    true,
    '$150k - $200k',
    'recommended',
    85,
    ARRAY['Python', 'LangGraph', 'CrewAI', 'Kubernetes', 'PostgreSQL', 'AI/ML'],
    ARRAY[]::TEXT[],
    ARRAY['multi-agent-systems', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/ai-engineer-multi-agent',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc02'::uuid,
    'Full-Stack Developer - AI-Native Applications',
    'StartupXYZ',
    'Join our team building AI-native applications using Cursor, Supabase, and modern web technologies. You will work on fast-moving projects with iterative development.',
    'full_time',
    'entry',
    'Remote',
    true,
    '$100k - $130k',
    'recommended',
    75,
    ARRAY['TypeScript', 'Next.js', 'Supabase', 'PostgreSQL', 'React'],
    ARRAY[]::TEXT[],
    ARRAY['vibe-coding-cursor-supabase', 'ai-native-software-delivery-pipelines'],
    'https://example.com/jobs/fullstack-ai-native',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc03'::uuid,
    'Senior AI Visibility Specialist',
    'Digital Marketing Agency',
    'Lead AI visibility optimization for enterprise clients. You will implement llms.txt, structured data, and content engineering strategies to improve AI Overview visibility.',
    'full_time',
    'senior',
    'New York, NY',
    false,
    '$120k - $160k',
    'recommended',
    90,
    ARRAY['SEO', 'AI Visibility', 'Content Strategy', 'Structured Data', 'Analytics'],
    ARRAY[]::TEXT[],
    ARRAY['ai-visibility', 'seo-to-aeo', 'llm-first-websites'],
    'https://example.com/jobs/ai-visibility-specialist',
    true,
    true
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc04'::uuid,
    'E-commerce AI Engineer',
    'EcomTech Solutions',
    'Build AI-driven e-commerce features including recommender systems, conversational commerce, and 3D product experiences.',
    'full_time',
    'mid',
    'Remote',
    true,
    '$130k - $170k',
    'recommended',
    80,
    ARRAY['Python', 'Machine Learning', 'E-commerce', 'Recommendation Systems', 'Three.js'],
    ARRAY[]::TEXT[],
    ARRAY['ai-recommender-systems', 'agentic-commerce', '3d-for-ecommerce'],
    'https://example.com/jobs/ecommerce-ai-engineer',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc05'::uuid,
    'AI Governance Consultant',
    'ComplianceTech',
    'Help clients navigate EU AI Act compliance and implement governance frameworks for AI systems.',
    'contract',
    'senior',
    'Remote',
    true,
    '$150/hour',
    'recommended',
    70,
    ARRAY['AI Governance', 'EU AI Act', 'Compliance', 'Risk Assessment', 'Documentation'],
    ARRAY[]::TEXT[],
    ARRAY['ai-governance-eu-ai-act'],
    'https://example.com/jobs/ai-governance-consultant',
    true,
    false
  ),
  (
    'c1b2c3d4-e5f6-4789-a012-3456789abc06'::uuid,
    'Stretch Role: Lead AI Architect',
    'Enterprise AI Corp',
    'Lead architecture for enterprise AI systems. Requires deep experience with multi-agent systems, RAG, and production deployment.',
    'full_time',
    'lead',
    'Remote',
    true,
    '$200k - $250k',
    'stretch',
    60,
    ARRAY['Multi-Agent Systems', 'RAG', 'Kubernetes', 'MLOps', 'System Design'],
    ARRAY['Enterprise Architecture', 'Team Leadership'],
    ARRAY['multi-agent-systems', 'agentic-rag', 'problem-shooting-change-drift-failure-multi-agent-systems'],
    'https://example.com/jobs/lead-ai-architect',
    true,
    false
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  company = EXCLUDED.company,
  description = EXCLUDED.description,
  job_type = EXCLUDED.job_type,
  experience_level = EXCLUDED.experience_level,
  location = EXCLUDED.location,
  is_remote = EXCLUDED.is_remote,
  salary_range = EXCLUDED.salary_range,
  status = EXCLUDED.status,
  matching_score = EXCLUDED.matching_score,
  skills = EXCLUDED.skills,
  skills_missing = EXCLUDED.skills_missing,
  recommended_for_courses = EXCLUDED.recommended_for_courses,
  external_url = EXCLUDED.external_url,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = NOW();

-- Insert sample offers with hardcoded deterministic UUIDs
INSERT INTO offers (
  id, title, provider, description, category, discount_text, discount_type, discount_value,
  discount_code, external_url, eligibility, recommended_for_courses, original_price,
  discounted_price, features, is_active, is_recommended, expiration_date, max_usage
)
VALUES
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc01'::uuid,
    'Supabase Pro - 50% off first 3 months',
    'Supabase',
    'Get 50% off Supabase Pro plan for the first 3 months. Perfect for building full-stack apps with auth, database, and storage.',
    'database',
    '50% off first 3 months',
    'percentage',
    50.00,
    'STUDENT50',
    'https://supabase.com/pricing',
    'New users only',
    ARRAY['vibe-coding-cursor-supabase', 'ai-native-software-delivery-pipelines'],
    '$25/month',
    '$12.50/month (first 3 months)',
    ARRAY['Unlimited API requests', '500GB database space', '50GB file storage', 'Priority support'],
    true,
    true,
    NOW() + INTERVAL '90 days',
    100
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc02'::uuid,
    'OpenAI API Credits - $100 free',
    'OpenAI',
    'Get $100 in free OpenAI API credits to build AI features. Perfect for experimenting with GPT-4, Whisper, and DALL-E.',
    'ai_llm',
    '$100 free credits',
    'free_credits',
    100.00,
    'STUDENT100',
    'https://platform.openai.com/signup',
    'New users only, requires student email',
    ARRAY['prompt-engineering', 'agentic-rag', 'multi-agent-systems'],
    '$0.01/1K tokens',
    '$100 free',
    ARRAY['Access to GPT-4', 'Whisper API', 'DALL-E API', 'Embeddings API'],
    true,
    true,
    NOW() + INTERVAL '60 days',
    50
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc03'::uuid,
    'Vercel Pro - Extended Trial',
    'Vercel',
    'Get 30 days free trial of Vercel Pro (normally 14 days). Deploy Next.js apps with zero configuration.',
    'hosting',
    '30 days free trial',
    'extended_trial',
    NULL,
    NULL,
    'New users only',
    ARRAY['vibe-coding-cursor-supabase', 'llm-first-websites'],
    '$20/month',
    'Free for 30 days',
    ARRAY['Unlimited deployments', '100GB bandwidth', 'Team collaboration', 'Analytics'],
    true,
    false,
    NOW() + INTERVAL '120 days',
    NULL
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc04'::uuid,
    'Pinecone Starter - 20% off',
    'Pinecone',
    'Get 20% off Pinecone Starter plan for vector database needs. Perfect for RAG applications.',
    'vector_database',
    '20% off first year',
    'percentage',
    20.00,
    'RAG20',
    'https://www.pinecone.io/pricing',
    'New users only',
    ARRAY['agentic-rag', 'multi-agent-systems'],
    '$70/month',
    '$56/month (first year)',
    ARRAY['1M vectors', '5GB storage', 'Basic support'],
    true,
    true,
    NOW() + INTERVAL '180 days',
    200
  ),
  (
    'd1b2c3d4-e5f6-4789-a012-3456789abc05'::uuid,
    'LangSmith Monitoring - Free Tier Upgrade',
    'LangChain',
    'Upgrade to LangSmith Pro features for free. Monitor and debug LangGraph applications.',
    'observability',
    'Free Pro tier upgrade',
    'tier_upgrade',
    NULL,
    NULL,
    'Students only',
    ARRAY['multi-agent-systems', 'agentic-rag'],
    '$99/month',
    'Free',
    ARRAY['Advanced tracing', 'Team collaboration', 'Custom dashboards', 'Priority support'],
    true,
    false,
    NOW() + INTERVAL '90 days',
    50
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  discount_text = EXCLUDED.discount_text,
  discount_type = EXCLUDED.discount_type,
  discount_value = EXCLUDED.discount_value,
  discount_code = EXCLUDED.discount_code,
  external_url = EXCLUDED.external_url,
  eligibility = EXCLUDED.eligibility,
  recommended_for_courses = EXCLUDED.recommended_for_courses,
  original_price = EXCLUDED.original_price,
  discounted_price = EXCLUDED.discounted_price,
  features = EXCLUDED.features,
  is_active = EXCLUDED.is_active,
  is_recommended = EXCLUDED.is_recommended,
  expiration_date = EXCLUDED.expiration_date,
  max_usage = EXCLUDED.max_usage,
  updated_at = NOW();

COMMIT;
