-- Seed user-dependent data
-- NOTE: These tables require existing profiles, student_profiles, etc. from auth.users
-- This script provides example queries that can be run AFTER users have signed up
-- 
-- Dependencies:
-- - profiles (depends on auth.users - cannot be seeded)
-- - student_profiles (depends on profiles)
-- - recruiter_profiles (depends on profiles)
-- - portfolio_projects (depends on student_profiles)
-- - course_enrollments (depends on courses + student_profiles)
-- - questions (depends on student_profiles)
-- - answers (depends on questions + profiles)
-- - event_presentations (depends on events + student_profiles + portfolio_projects)
-- - event_attendance (depends on events + profiles)
-- - contact_requests (depends on recruiter_profiles + student_profiles)
--
-- consent_events and admin_audit_log are typically auto-generated by triggers

BEGIN;

-- Example: Seed course enrollments (requires courses + student_profiles)
-- Uncomment and modify when you have student profiles:
/*
INSERT INTO course_enrollments (course_id, student_profile_id, progress_percentage)
SELECT 
  c.id,
  sp.id,
  FLOOR(RANDOM() * 100)::INTEGER
FROM courses c
CROSS JOIN student_profiles sp
WHERE c.is_published = true
LIMIT 50
ON CONFLICT (course_id, student_profile_id) DO NOTHING;
*/

-- Example: Seed portfolio projects (requires student_profiles)
-- Uncomment and modify when you have student profiles:
/*
INSERT INTO portfolio_projects (student_profile_id, title, description, github_url, demo_url, visibility)
SELECT 
  sp.id,
  'Sample Project ' || ROW_NUMBER() OVER (PARTITION BY sp.id),
  'A sample portfolio project showcasing AI/ML skills.',
  'https://github.com/example/project',
  'https://example.com/demo',
  CASE (RANDOM() * 3)::INTEGER
    WHEN 0 THEN 'private'
    WHEN 1 THEN 'recruiters_only'
    ELSE 'public'
  END::visibility_level
FROM student_profiles sp
LIMIT 20
ON CONFLICT DO NOTHING;
*/

-- Example: Seed questions (requires student_profiles)
-- Uncomment and modify when you have student profiles:
/*
INSERT INTO questions (student_profile_id, context_type, context_id, title, body)
SELECT 
  sp.id,
  'lesson'::question_context_type,
  'lesson-001',
  'Question about ' || c.title,
  'I have a question about this lesson. Can someone help?'
FROM student_profiles sp
CROSS JOIN courses c
WHERE c.is_published = true
LIMIT 10
ON CONFLICT DO NOTHING;
*/

-- Example: Seed event presentations (requires events + student_profiles + portfolio_projects)
-- Uncomment and modify when you have the required data:
/*
INSERT INTO event_presentations (event_id, student_profile_id, portfolio_project_id, presentation_title, presentation_order)
SELECT 
  e.id,
  sp.id,
  pp.id,
  pp.title,
  ROW_NUMBER() OVER (PARTITION BY e.id ORDER BY pp.created_at)
FROM events e
CROSS JOIN student_profiles sp
JOIN portfolio_projects pp ON pp.student_profile_id = sp.id
WHERE e.event_type = 'demo_day'
  AND e.start_time > NOW()
  AND pp.visibility IN ('public', 'recruiters_only')
LIMIT 10
ON CONFLICT DO NOTHING;
*/

-- Example: Seed event attendance (requires events + profiles)
-- Uncomment and modify when you have profiles:
/*
INSERT INTO event_attendance (event_id, profile_id, rsvp_status)
SELECT 
  e.id,
  p.id,
  CASE (RANDOM() * 3)::INTEGER
    WHEN 0 THEN 'pending'
    WHEN 1 THEN 'confirmed'
    ELSE 'cancelled'
  END
FROM events e
CROSS JOIN profiles p
WHERE e.start_time > NOW()
LIMIT 30
ON CONFLICT (event_id, profile_id) DO NOTHING;
*/

-- Example: Seed contact requests (requires recruiter_profiles + student_profiles)
-- Uncomment and modify when you have the required data:
/*
INSERT INTO contact_requests (recruiter_profile_id, student_profile_id, status, message)
SELECT 
  rp.id,
  sp.id,
  CASE (RANDOM() * 4)::INTEGER
    WHEN 0 THEN 'pending'::contact_request_status
    WHEN 1 THEN 'approved'::contact_request_status
    WHEN 2 THEN 'rejected'::contact_request_status
    ELSE 'withdrawn'::contact_request_status
  END,
  'I would like to connect regarding potential opportunities.'
FROM recruiter_profiles rp
CROSS JOIN student_profiles sp
WHERE sp.visibility IN ('public', 'recruiters_only')
LIMIT 10
ON CONFLICT DO NOTHING;
*/

COMMIT;
