-- Seed user-dependent data
-- NOTE: These tables require existing profiles, student_profiles, etc. from auth.users
-- This script provides example queries that can be run AFTER users have signed up
-- Uses deterministic UUIDs to reference parent records (courses, events, etc.)

BEGIN;

-- Helper function to generate deterministic UUID from string
-- Same function as used in other seed scripts
CREATE OR REPLACE FUNCTION deterministic_uuid(input_text TEXT)
RETURNS UUID AS $$
BEGIN
  RETURN uuid_generate_v5('6ba7b813-9dad-11d1-80b4-00c04fd430c8'::uuid, input_text);
EXCEPTION
  WHEN OTHERS THEN
    RETURN ('00000000-0000-0000-0000-' || substr(md5(input_text), 1, 12))::uuid;
END;
$$ LANGUAGE plpgsql;

-- Ensure uuid extension is available
DO $$ 
BEGIN
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END $$;

-- Dependencies:
-- - profiles (depends on auth.users - cannot be seeded)
-- - student_profiles (depends on profiles)
-- - recruiter_profiles (depends on profiles)
-- - portfolio_projects (depends on student_profiles)
-- - course_enrollments (depends on courses + student_profiles)
-- - questions (depends on student_profiles)
-- - answers (depends on questions + profiles)
-- - event_presentations (depends on events + student_profiles + portfolio_projects)
-- - event_attendance (depends on events + profiles)
-- - contact_requests (depends on recruiter_profiles + student_profiles)
--
-- consent_events and admin_audit_log are typically auto-generated by triggers

BEGIN;

-- Example: Seed course enrollments (requires courses + student_profiles)
-- Uses deterministic UUIDs to reference courses
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  course_id_var UUID;
BEGIN
  -- Reference course by deterministic UUID
  SELECT id INTO course_id_var 
  FROM courses 
  WHERE id = deterministic_uuid('course:multi-agent-systems');
  
  -- Insert enrollments using the captured course ID
  INSERT INTO course_enrollments (course_id, student_profile_id, progress_percentage)
  SELECT 
    course_id_var,
    sp.id,
    FLOOR(RANDOM() * 100)::INTEGER
  FROM student_profiles sp
  LIMIT 10
  ON CONFLICT (course_id, student_profile_id) DO NOTHING;
END $$;
*/

-- Example: Seed portfolio projects (requires student_profiles)
-- Uncomment and modify when you have student profiles:
/*
INSERT INTO portfolio_projects (student_profile_id, title, description, github_url, demo_url, visibility)
SELECT 
  sp.id,
  'Sample Project ' || ROW_NUMBER() OVER (PARTITION BY sp.id),
  'A sample portfolio project showcasing AI/ML skills.',
  'https://github.com/example/project',
  'https://example.com/demo',
  CASE (RANDOM() * 3)::INTEGER
    WHEN 0 THEN 'private'
    WHEN 1 THEN 'recruiters_only'
    ELSE 'public'
  END::visibility_level
FROM student_profiles sp
LIMIT 20
ON CONFLICT DO NOTHING;
*/

-- Example: Seed questions (requires student_profiles)
-- Uncomment and modify when you have student profiles:
/*
INSERT INTO questions (student_profile_id, context_type, context_id, title, body)
SELECT 
  sp.id,
  'lesson'::question_context_type,
  'lesson-001',
  'Question about ' || c.title,
  'I have a question about this lesson. Can someone help?'
FROM student_profiles sp
CROSS JOIN courses c
WHERE c.is_published = true
LIMIT 10
ON CONFLICT DO NOTHING;
*/

-- Example: Seed event presentations (requires events + student_profiles + portfolio_projects)
-- Uses deterministic UUIDs to reference events
-- Uncomment and modify when you have the required data:
/*
DO $$
DECLARE
  event_id_var UUID;
BEGIN
  -- Reference event by deterministic UUID
  SELECT id INTO event_id_var 
  FROM events 
  WHERE id = deterministic_uuid('event:Q1 2025 Demo Day');
  
  -- Insert presentations using the captured event ID
  INSERT INTO event_presentations (event_id, student_profile_id, portfolio_project_id, presentation_title, presentation_order)
  SELECT 
    event_id_var,
    sp.id,
    pp.id,
    pp.title,
    ROW_NUMBER() OVER (ORDER BY pp.created_at)
  FROM student_profiles sp
  JOIN portfolio_projects pp ON pp.student_profile_id = sp.id
  WHERE pp.visibility IN ('public', 'recruiters_only')
  LIMIT 10
  ON CONFLICT DO NOTHING;
END $$;
*/

-- Example: Seed event attendance (requires events + profiles)
-- Uncomment and modify when you have profiles:
/*
INSERT INTO event_attendance (event_id, profile_id, rsvp_status)
SELECT 
  e.id,
  p.id,
  CASE (RANDOM() * 3)::INTEGER
    WHEN 0 THEN 'pending'
    WHEN 1 THEN 'confirmed'
    ELSE 'cancelled'
  END
FROM events e
CROSS JOIN profiles p
WHERE e.start_time > NOW()
LIMIT 30
ON CONFLICT (event_id, profile_id) DO NOTHING;
*/

-- Example: Seed contact requests (requires recruiter_profiles + student_profiles)
-- Uncomment and modify when you have the required data:
/*
INSERT INTO contact_requests (recruiter_profile_id, student_profile_id, status, message)
SELECT 
  rp.id,
  sp.id,
  CASE (RANDOM() * 4)::INTEGER
    WHEN 0 THEN 'pending'::contact_request_status
    WHEN 1 THEN 'approved'::contact_request_status
    WHEN 2 THEN 'rejected'::contact_request_status
    ELSE 'withdrawn'::contact_request_status
  END,
  'I would like to connect regarding potential opportunities.'
FROM recruiter_profiles rp
CROSS JOIN student_profiles sp
WHERE sp.visibility IN ('public', 'recruiters_only')
LIMIT 10
  ON CONFLICT DO NOTHING;
END $$;
*/

COMMIT;
