-- Seed consent_events: audit trail for visibility changes and contact approvals
-- NOTE: This table is typically auto-generated by triggers, but this script provides
-- example queries for seeding historical consent events for testing/development
-- Requires existing student_profiles, portfolio_projects, and contact_requests
--
-- NOTE: This script should be run using a direct database connection (psql)
-- which bypasses Row Level Security (RLS). The connection string should be
-- the "Direct connection" or "Transaction pooler" from Supabase Dashboard.

BEGIN;

-- Dependencies:
-- - student_profiles (depends on profiles, which depend on auth.users)
-- - portfolio_projects (depends on student_profiles)
-- - contact_requests (depends on recruiter_profiles + student_profiles)
-- - consent_events (typically auto-generated by triggers)

-- IMPORTANT: Consent events are typically created automatically by triggers when:
-- 1. Student profile visibility changes (private <-> recruiters_only <-> public)
-- 2. Portfolio project visibility changes (private <-> recruiters_only <-> public)
-- 3. Contact requests are approved (pending -> approved)

-- Example: Seed consent_events for student profile visibility changes
-- Simulates historical visibility changes for student profiles
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  student_record RECORD;
  profile_record RECORD;
  visibility_levels TEXT[] := ARRAY['private', 'recruiters_only', 'public'];
  old_visibility TEXT;
  new_visibility TEXT;
  event_time TIMESTAMPTZ;
  change_counter INTEGER;
BEGIN
  -- Loop through student profiles and create visibility change events
  FOR student_record IN 
    SELECT sp.id as student_profile_id, sp.profile_id, sp.visibility, sp.created_at
    FROM student_profiles sp
    ORDER BY sp.created_at
    LIMIT 15
  LOOP
    -- Get the profile to access user_id
    SELECT p.id, p.user_id INTO profile_record
    FROM profiles p
    WHERE p.id = student_record.profile_id;
    
    IF profile_record.user_id IS NOT NULL THEN
      -- Create 1-3 visibility change events per student
      change_counter := 0;
      old_visibility := 'private'; -- Assume starting from private
      event_time := student_record.created_at + INTERVAL '1 day';
      
      FOR change_counter IN 1..(1 + FLOOR(RANDOM() * 3)::INTEGER)
      LOOP
        -- Determine new visibility (different from old)
        new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
        WHILE new_visibility = old_visibility LOOP
          new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
        END LOOP;
        
        -- Insert consent event for visibility change
        INSERT INTO consent_events (
          user_id,
          profile_id,
          event_type,
          resource_type,
          resource_id,
          old_value,
          new_value,
          metadata,
          created_at
        )
        VALUES (
          profile_record.user_id,
          student_record.profile_id,
          'visibility_change',
          'student_profile',
          student_record.student_profile_id,
          old_visibility,
          new_visibility,
          jsonb_build_object(
            'profile_id', student_record.student_profile_id,
            'changed_at', event_time,
            'change_number', change_counter
          ),
          event_time
        );
        
        old_visibility := new_visibility;
        event_time := event_time + INTERVAL '7 days' + (RANDOM() * INTERVAL '14 days');
      END LOOP;
    END IF;
  END LOOP;
  
  RAISE NOTICE 'Seeded consent_events for student profile visibility changes';
END $$;
*/

-- Example: Seed consent_events for portfolio project visibility changes
-- Simulates historical visibility changes for portfolio projects
-- Uncomment and modify when you have portfolio projects:
/*
DO $$
DECLARE
  project_record RECORD;
  profile_record RECORD;
  visibility_levels TEXT[] := ARRAY['private', 'recruiters_only', 'public'];
  old_visibility TEXT;
  new_visibility TEXT;
  event_time TIMESTAMPTZ;
BEGIN
  -- Loop through portfolio projects and create visibility change events
  FOR project_record IN 
    SELECT pp.id as project_id, pp.student_profile_id, pp.visibility, pp.title, pp.created_at
    FROM portfolio_projects pp
    ORDER BY pp.created_at
    LIMIT 20
  LOOP
    -- Get the profile to access user_id
    SELECT p.id, p.user_id INTO profile_record
    FROM profiles p
    JOIN student_profiles sp ON sp.profile_id = p.id
    WHERE sp.id = project_record.student_profile_id;
    
    IF profile_record.user_id IS NOT NULL THEN
      -- Create 1-2 visibility change events per project
      old_visibility := 'private'; -- Assume starting from private
      event_time := project_record.created_at + INTERVAL '2 days';
      
      -- First visibility change
      new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
      WHILE new_visibility = old_visibility LOOP
        new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
      END LOOP;
      
      INSERT INTO consent_events (
        user_id,
        profile_id,
        event_type,
        resource_type,
        resource_id,
        old_value,
        new_value,
        metadata,
        created_at
      )
      VALUES (
        profile_record.user_id,
        profile_record.id,
        'visibility_change',
        'portfolio_project',
        project_record.project_id,
        old_visibility,
        new_visibility,
        jsonb_build_object(
          'project_id', project_record.project_id,
          'project_title', project_record.title,
          'changed_at', event_time
        ),
        event_time
      );
      
      -- Optional second visibility change (30% chance)
      IF RANDOM() > 0.7 THEN
        old_visibility := new_visibility;
        new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
        WHILE new_visibility = old_visibility LOOP
          new_visibility := visibility_levels[1 + FLOOR(RANDOM() * (array_length(visibility_levels, 1) - 1))::INTEGER];
        END LOOP;
        
        event_time := event_time + INTERVAL '14 days' + (RANDOM() * INTERVAL '30 days');
        
        INSERT INTO consent_events (
          user_id,
          profile_id,
          event_type,
          resource_type,
          resource_id,
          old_value,
          new_value,
          metadata,
          created_at
        )
        VALUES (
          profile_record.user_id,
          profile_record.id,
          'visibility_change',
          'portfolio_project',
          project_record.project_id,
          old_visibility,
          new_visibility,
          jsonb_build_object(
            'project_id', project_record.project_id,
            'project_title', project_record.title,
            'changed_at', event_time
          ),
          event_time
        );
      END IF;
    END IF;
  END LOOP;
  
  RAISE NOTICE 'Seeded consent_events for portfolio project visibility changes';
END $$;
*/

-- Example: Seed consent_events for contact request approvals
-- Simulates historical contact request approvals
-- Uncomment and modify when you have contact_requests:
/*
DO $$
DECLARE
  contact_record RECORD;
  profile_record RECORD;
  approval_time TIMESTAMPTZ;
BEGIN
  -- Loop through approved contact requests and create consent events
  FOR contact_record IN 
    SELECT cr.id as contact_request_id, cr.student_profile_id, cr.recruiter_profile_id, cr.status, cr.created_at
    FROM contact_requests cr
    WHERE cr.status = 'approved'
    ORDER BY cr.created_at
    LIMIT 10
  LOOP
    -- Get the profile to access user_id
    SELECT p.id, p.user_id INTO profile_record
    FROM profiles p
    JOIN student_profiles sp ON sp.profile_id = p.id
    WHERE sp.id = contact_record.student_profile_id;
    
    IF profile_record.user_id IS NOT NULL THEN
      -- Approval time is typically shortly after request creation
      approval_time := contact_record.created_at + INTERVAL '1 day' + (RANDOM() * INTERVAL '3 days');
      
      INSERT INTO consent_events (
        user_id,
        profile_id,
        event_type,
        resource_type,
        resource_id,
        old_value,
        new_value,
        metadata,
        created_at
      )
      VALUES (
        profile_record.user_id,
        profile_record.id,
        'contact_approval',
        'contact_request',
        contact_record.contact_request_id,
        'pending',
        'approved',
        jsonb_build_object(
          'contact_request_id', contact_record.contact_request_id,
          'recruiter_profile_id', contact_record.recruiter_profile_id,
          'approved_at', approval_time
        ),
        approval_time
      );
    END IF;
  END LOOP;
  
  RAISE NOTICE 'Seeded consent_events for contact request approvals';
END $$;
*/

-- Alternative: Simple seed with basic consent events
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  student_record RECORD;
  profile_record RECORD;
  event_time TIMESTAMPTZ;
BEGIN
  -- Create one visibility change event per student profile
  FOR student_record IN 
    SELECT sp.id as student_profile_id, sp.profile_id, sp.created_at
    FROM student_profiles sp
    ORDER BY sp.created_at
    LIMIT 10
  LOOP
    -- Get the profile to access user_id
    SELECT p.id, p.user_id INTO profile_record
    FROM profiles p
    WHERE p.id = student_record.profile_id;
    
    IF profile_record.user_id IS NOT NULL THEN
      event_time := student_record.created_at + INTERVAL '1 day';
      
      INSERT INTO consent_events (
        user_id,
        profile_id,
        event_type,
        resource_type,
        resource_id,
        old_value,
        new_value,
        metadata,
        created_at
      )
      VALUES (
        profile_record.user_id,
        student_record.profile_id,
        'visibility_change',
        'student_profile',
        student_record.student_profile_id,
        'private',
        'recruiters_only',
        jsonb_build_object(
          'profile_id', student_record.student_profile_id,
          'changed_at', event_time
        ),
        event_time
      );
    END IF;
  END LOOP;
END $$;
*/

COMMIT;
