-- Seed email_outbox: email queue for weekly learning and jobs emails
-- NOTE: This table is typically auto-generated by cron jobs, but this script provides
-- example queries for seeding email outbox entries for testing/development
-- Requires existing student_profiles from auth.users
--
-- NOTE: This script should be run using a direct database connection (psql)
-- which bypasses Row Level Security (RLS). The connection string should be
-- the "Direct connection" or "Transaction pooler" from Supabase Dashboard.

BEGIN;

-- Dependencies:
-- - student_profiles (depends on profiles, which depend on auth.users)
-- - email_outbox (typically auto-generated by cron jobs)

-- IMPORTANT: 
-- - email_outbox is typically created automatically by cron jobs (weekly-learning-emails, weekly-jobs-emails)
-- - dedupe_key has a UNIQUE constraint: format is 'email_type:YYYY-WW:student_profile_id'
-- - The dedupe_key uses ISO week format (YYYY-WW) to allow safe re-runs within the same week
-- - Status can be: 'queued', 'sent', 'failed'
-- - Only system/admins can insert emails (RLS policy)

-- Example: Seed email_outbox for students
-- Creates realistic email queue entries with various statuses
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  student_record RECORD;
  profile_record RECORD;
  email_type_var TEXT;
  dedupe_key_var TEXT;
  template_key_var VARCHAR(255);
  subject_var TEXT;
  payload_var JSONB;
  status_var email_status;
  sent_at_var TIMESTAMPTZ;
  created_at_var TIMESTAMPTZ;
  week_number INTEGER;
  year_number INTEGER;
  week_str TEXT;
  email_counter INTEGER := 0;
  
  -- Get current ISO week number
  current_date_var DATE := CURRENT_DATE;
BEGIN
  -- Calculate ISO week number
  year_number := EXTRACT(YEAR FROM current_date_var);
  week_number := EXTRACT(WEEK FROM current_date_var);
  week_str := LPAD(week_number::TEXT, 2, '0');
  
  -- Loop through student profiles and create email entries
  FOR student_record IN 
    SELECT sp.id as student_profile_id, sp.profile_id
    FROM student_profiles sp
    WHERE sp.weekly_learning_emails_enabled = true 
       OR sp.weekly_jobs_emails_enabled = true
    ORDER BY sp.created_at
    LIMIT 20
  LOOP
    -- Get profile to access user email
    SELECT p.id, au.email INTO profile_record
    FROM profiles p
    JOIN auth.users au ON au.id = p.user_id
    WHERE p.id = student_record.profile_id;
    
    IF profile_record.email IS NOT NULL THEN
      -- Create weekly learning email (if enabled)
      IF (RANDOM() > 0.3) THEN -- 70% chance
        email_type_var := 'weekly_learning';
        template_key_var := 'weekly_next_lesson';
        dedupe_key_var := email_type_var || ':' || year_number || '-W' || week_str || ':' || student_record.student_profile_id::TEXT;
        subject_var := 'Continue learning: Next lesson in your course';
        created_at_var := NOW() - INTERVAL '2 days' + (RANDOM() * INTERVAL '2 days');
        
        -- Determine status: 60% sent, 30% queued, 10% failed
        IF RANDOM() < 0.6 THEN
          status_var := 'sent'::email_status;
          sent_at_var := created_at_var + INTERVAL '1 hour';
        ELSIF RANDOM() < 0.9 THEN
          status_var := 'queued'::email_status;
          sent_at_var := NULL;
        ELSE
          status_var := 'failed'::email_status;
          sent_at_var := NULL;
        END IF;
        
        payload_var := jsonb_build_object(
          'name', 'Student',
          'courseTitle', 'Multi-Agent Systems',
          'courseSlug', 'multi-agent-systems',
          'lastLesson', 'Module 1: Foundations',
          'lastLessonSlug', 'Module_01_Foundations',
          'nextLesson', 'Module 2: Frameworks',
          'nextLessonSlug', 'Module_02_Frameworks',
          'emailTakeaway', 'Learn how to deploy multi-agent systems at scale',
          'emailAction', 'Continue to Module 2',
          'progressPercentage', 25,
          'unsubscribeToken', 'token-' || gen_random_uuid()::TEXT
        );
        
        INSERT INTO email_outbox (
          student_profile_id,
          template_key,
          email_type,
          dedupe_key,
          to_email,
          subject,
          payload,
          status,
          sent_at,
          created_at,
          attempt_count,
          next_attempt_at
        )
        VALUES (
          student_record.student_profile_id,
          template_key_var,
          email_type_var,
          dedupe_key_var,
          profile_record.email,
          subject_var,
          payload_var,
          status_var,
          sent_at_var,
          created_at_var,
          CASE WHEN status_var = 'sent' THEN 1 ELSE 0 END,
          CASE WHEN status_var = 'queued' THEN NOW() ELSE created_at_var END
        )
        ON CONFLICT (dedupe_key) DO NOTHING;
        
        email_counter := email_counter + 1;
      END IF;
      
      -- Create weekly jobs email (if enabled, 50% chance)
      IF (RANDOM() > 0.5) THEN
        email_type_var := 'weekly_jobs';
        template_key_var := 'weekly_jobs';
        dedupe_key_var := email_type_var || ':' || year_number || '-W' || week_str || ':' || student_record.student_profile_id::TEXT;
        subject_var := 'New job opportunities for you';
        created_at_var := NOW() - INTERVAL '1 day' + (RANDOM() * INTERVAL '1 day');
        
        -- Determine status: 70% sent, 20% queued, 10% failed
        IF RANDOM() < 0.7 THEN
          status_var := 'sent'::email_status;
          sent_at_var := created_at_var + INTERVAL '30 minutes';
        ELSIF RANDOM() < 0.9 THEN
          status_var := 'queued'::email_status;
          sent_at_var := NULL;
        ELSE
          status_var := 'failed'::email_status;
          sent_at_var := NULL;
        END IF;
        
        payload_var := jsonb_build_object(
          'name', 'Student',
          'jobs', jsonb_build_array(
            jsonb_build_object(
              'title', 'AI Engineer - Multi-Agent Systems',
              'company', 'TechCorp AI',
              'matchingScore', 85
            ),
            jsonb_build_object(
              'title', 'Full-Stack Developer - AI-Native Applications',
              'company', 'StartupXYZ',
              'matchingScore', 75
            )
          ),
          'unsubscribeToken', 'token-' || gen_random_uuid()::TEXT
        );
        
        INSERT INTO email_outbox (
          student_profile_id,
          template_key,
          email_type,
          dedupe_key,
          to_email,
          subject,
          payload,
          status,
          sent_at,
          created_at,
          attempt_count,
          next_attempt_at,
          last_error
        )
        VALUES (
          student_record.student_profile_id,
          template_key_var,
          email_type_var,
          dedupe_key_var,
          profile_record.email,
          subject_var,
          payload_var,
          status_var,
          sent_at_var,
          created_at_var,
          CASE 
            WHEN status_var = 'sent' THEN 1
            WHEN status_var = 'failed' THEN 3
            ELSE 0
          END,
          CASE 
            WHEN status_var = 'queued' THEN NOW()
            WHEN status_var = 'failed' THEN NOW() + INTERVAL '1 hour'
            ELSE created_at_var
          END,
          CASE WHEN status_var = 'failed' THEN 'SMTP error: Connection timeout' ELSE NULL END
        )
        ON CONFLICT (dedupe_key) DO NOTHING;
        
        email_counter := email_counter + 1;
      END IF;
    END IF;
  END LOOP;
  
  RAISE NOTICE 'Seeded % email outbox entries', email_counter;
END $$;
*/

-- Alternative: Simple seed with basic email entries
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  student_record RECORD;
  profile_record RECORD;
  year_number INTEGER;
  week_number INTEGER;
  week_str TEXT;
  dedupe_key_var TEXT;
BEGIN
  year_number := EXTRACT(YEAR FROM CURRENT_DATE);
  week_number := EXTRACT(WEEK FROM CURRENT_DATE);
  week_str := LPAD(week_number::TEXT, 2, '0');
  
  -- Create one weekly learning email per student
  FOR student_record IN 
    SELECT sp.id as student_profile_id, sp.profile_id
    FROM student_profiles sp
    WHERE sp.weekly_learning_emails_enabled = true
    ORDER BY sp.created_at
    LIMIT 10
  LOOP
    -- Get profile to access user email
    SELECT p.id, au.email INTO profile_record
    FROM profiles p
    JOIN auth.users au ON au.id = p.user_id
    WHERE p.id = student_record.profile_id;
    
    IF profile_record.email IS NOT NULL THEN
      dedupe_key_var := 'weekly_learning:' || year_number || '-W' || week_str || ':' || student_record.student_profile_id::TEXT;
      
      INSERT INTO email_outbox (
        student_profile_id,
        template_key,
        email_type,
        dedupe_key,
        to_email,
        subject,
        payload,
        status,
        attempt_count,
        next_attempt_at
      )
      VALUES (
        student_record.student_profile_id,
        'weekly_next_lesson',
        'weekly_learning',
        dedupe_key_var,
        profile_record.email,
        'Continue learning: Next lesson in your course',
        jsonb_build_object(
          'name', 'Student',
          'courseTitle', 'Multi-Agent Systems',
          'progressPercentage', 50
        ),
        'queued'::email_status,
        0,
        NOW()
      )
      ON CONFLICT (dedupe_key) DO NOTHING;
    END IF;
  END LOOP;
END $$;
*/

-- Example: Create emails for previous weeks (historical data)
-- Uncomment and modify when you have student profiles:
/*
DO $$
DECLARE
  student_record RECORD;
  profile_record RECORD;
  week_offset INTEGER;
  year_number INTEGER;
  week_number INTEGER;
  week_str TEXT;
  dedupe_key_var TEXT;
  created_at_var TIMESTAMPTZ;
  sent_at_var TIMESTAMPTZ;
BEGIN
  -- Create emails for the last 4 weeks
  FOR week_offset IN 1..4
  LOOP
    created_at_var := NOW() - (week_offset * INTERVAL '7 days');
    year_number := EXTRACT(YEAR FROM created_at_var);
    week_number := EXTRACT(WEEK FROM created_at_var);
    week_str := LPAD(week_number::TEXT, 2, '0');
    sent_at_var := created_at_var + INTERVAL '1 hour';
    
    FOR student_record IN 
      SELECT sp.id as student_profile_id, sp.profile_id
      FROM student_profiles sp
      WHERE sp.weekly_learning_emails_enabled = true
      ORDER BY RANDOM()
      LIMIT 5
    LOOP
      SELECT p.id, au.email INTO profile_record
      FROM profiles p
      JOIN auth.users au ON au.id = p.user_id
      WHERE p.id = student_record.profile_id;
      
      IF profile_record.email IS NOT NULL THEN
        dedupe_key_var := 'weekly_learning:' || year_number || '-W' || week_str || ':' || student_record.student_profile_id::TEXT;
        
        INSERT INTO email_outbox (
          student_profile_id,
          template_key,
          email_type,
          dedupe_key,
          to_email,
          subject,
          payload,
          status,
          sent_at,
          created_at,
          attempt_count,
          next_attempt_at
        )
        VALUES (
          student_record.student_profile_id,
          'weekly_next_lesson',
          'weekly_learning',
          dedupe_key_var,
          profile_record.email,
          'Continue learning: Next lesson in your course',
          jsonb_build_object(
            'name', 'Student',
            'courseTitle', 'Multi-Agent Systems',
            'progressPercentage', 25 + (week_offset * 10)
          ),
          'sent'::email_status,
          sent_at_var,
          created_at_var,
          1,
          created_at_var
        )
        ON CONFLICT (dedupe_key) DO NOTHING;
      END IF;
    END LOOP;
  END LOOP;
END $$;
*/

COMMIT;
