-- Seed payments: Payment history ledger (invoices and payment outcomes)
-- NOTE: This table is typically populated by Stripe webhooks (invoice.paid events)
-- This script provides example payment records that demonstrate the structure
-- NOTE: Payments require existing auth.users (user_id) and optionally subscriptions
--
-- NOTE: This script should be run using a direct database connection (psql)
-- which bypasses Row Level Security (RLS). The connection string should be
-- the "Direct connection" or "Transaction pooler" from Supabase Dashboard.

BEGIN;

-- Dependencies:
-- - auth.users (created via authentication)
-- - stripe_customers (optional - for stripe_customer_id references)
-- - subscriptions (optional - for stripe_subscription_id references)
-- - payments (depends on auth.users)

-- IMPORTANT: 
-- - Payments are typically auto-generated by Stripe webhooks (invoice.paid events)
-- - Payment IDs are Stripe payment_intent IDs (pi_...) or charge IDs (ch_...)
-- - Amount is stored in smallest currency unit (e.g., 3900 = £39.00 or $39.00)
-- - Currency codes: 'gbp', 'usd', 'eur', etc.
-- - Status values: 'succeeded', 'failed', 'pending', 'refunded'
-- - For seed data, we use example Stripe IDs (pi_... format)

-- Example 1: Seed payments for users with subscriptions
-- Creates realistic payment records linked to subscriptions
-- Uncomment and modify when you have users and subscriptions:
/*
DO $$
DECLARE
  subscription_record RECORD;
  payment_id_var TEXT;
  amount_var INTEGER;
  currency_var TEXT := 'gbp';
  status_var TEXT;
  payment_counter INTEGER;
  base_time TIMESTAMPTZ;
BEGIN
  -- Loop through active subscriptions
  FOR subscription_record IN 
    SELECT 
      s.id as subscription_id,
      s.user_id,
      s.stripe_customer_id,
      s.stripe_price_id,
      s.current_period_start,
      s.current_period_end
    FROM subscriptions s
    WHERE s.status IN ('active', 'trialing')
    LIMIT 10
  LOOP
    base_time := subscription_record.current_period_start;
    
    -- Create 1-3 payment records per subscription (monthly/annual payments)
    FOR payment_counter IN 1..(1 + FLOOR(RANDOM() * 2)::INTEGER) LOOP
      -- Generate payment intent ID (Stripe format: pi_...)
      payment_id_var := 'pi_' || substr(md5(random()::text || subscription_record.subscription_id || payment_counter::text), 1, 24);
      
      -- Determine amount based on plan (example: Essential = £39/month, Pro = £79/month)
      -- This is simplified - in reality, amount comes from Stripe invoice
      IF subscription_record.stripe_price_id LIKE '%essential%' THEN
        amount_var := 3900; -- £39.00
      ELSIF subscription_record.stripe_price_id LIKE '%pro%' THEN
        amount_var := 7900; -- £79.00
      ELSE
        amount_var := 3900 + FLOOR(RANDOM() * 4000)::INTEGER; -- £39-£79
      END IF;
      
      -- 90% succeeded, 5% failed, 5% pending
      IF RANDOM() < 0.9 THEN
        status_var := 'succeeded';
      ELSIF RANDOM() < 0.95 THEN
        status_var := 'failed';
      ELSE
        status_var := 'pending';
      END IF;
      
      -- Generate invoice ID (Stripe format: in_...)
      INSERT INTO payments (
        id,
        user_id,
        stripe_customer_id,
        amount,
        currency,
        status,
        stripe_invoice_id,
        stripe_subscription_id,
        created_at
      )
      VALUES (
        payment_id_var,
        subscription_record.user_id,
        subscription_record.stripe_customer_id,
        amount_var,
        currency_var,
        status_var,
        'in_' || substr(md5(random()::text || payment_id_var), 1, 24),
        subscription_record.subscription_id,
        base_time + INTERVAL '1 month' * (payment_counter - 1)
      )
      ON CONFLICT (id) DO UPDATE SET
        amount = EXCLUDED.amount,
        currency = EXCLUDED.currency,
        status = EXCLUDED.status,
        stripe_invoice_id = EXCLUDED.stripe_invoice_id,
        stripe_subscription_id = EXCLUDED.stripe_subscription_id;
    END LOOP;
  END LOOP;
END $$;
*/

-- Example 2: Seed payments for users with stripe_customers
-- Creates payment records for users who have Stripe customers but may not have subscriptions
-- Uncomment and modify when you have users and stripe_customers:
/*
DO $$
DECLARE
  customer_record RECORD;
  payment_id_var TEXT;
  amount_var INTEGER;
  currency_var TEXT;
  status_var TEXT;
  payment_counter INTEGER;
BEGIN
  -- Loop through Stripe customers
  FOR customer_record IN 
    SELECT 
      sc.user_id,
      sc.stripe_customer_id
    FROM stripe_customers sc
    LIMIT 5
  LOOP
    -- Create 1-2 payment records per customer
    FOR payment_counter IN 1..(1 + FLOOR(RANDOM() * 1)::INTEGER) LOOP
      -- Generate payment intent ID
      payment_id_var := 'pi_' || substr(md5(random()::text || customer_record.stripe_customer_id || payment_counter::text), 1, 24);
      
      -- Random amount between £10 and £100
      amount_var := 1000 + FLOOR(RANDOM() * 9000)::INTEGER;
      
      -- Random currency (mostly GBP, some USD)
      IF RANDOM() < 0.8 THEN
        currency_var := 'gbp';
      ELSE
        currency_var := 'usd';
        amount_var := amount_var * 1; -- USD amounts similar to GBP for seed data
      END IF;
      
      -- 85% succeeded, 10% failed, 5% pending
      IF RANDOM() < 0.85 THEN
        status_var := 'succeeded';
      ELSIF RANDOM() < 0.95 THEN
        status_var := 'failed';
      ELSE
        status_var := 'pending';
      END IF;
      
      INSERT INTO payments (
        id,
        user_id,
        stripe_customer_id,
        amount,
        currency,
        status,
        created_at
      )
      VALUES (
        payment_id_var,
        customer_record.user_id,
        customer_record.stripe_customer_id,
        amount_var,
        currency_var,
        status_var,
        NOW() - INTERVAL '1 day' * FLOOR(RANDOM() * 60)::INTEGER
      )
      ON CONFLICT (id) DO UPDATE SET
        amount = EXCLUDED.amount,
        currency = EXCLUDED.currency,
        status = EXCLUDED.status;
    END LOOP;
  END LOOP;
END $$;
*/

-- Example 3: Seed payments with specific scenarios
-- Demonstrates different payment statuses and amounts
-- Uncomment and modify when you have users:
/*
DO $$
DECLARE
  user_record RECORD;
  payment_id_var TEXT;
  customer_id_var TEXT;
  amount_var INTEGER;
  status_var TEXT;
  subscription_id_var TEXT;
BEGIN
  -- Get users (assuming they have profiles)
  FOR user_record IN 
    SELECT DISTINCT p.user_id
    FROM profiles p
    LIMIT 3
  LOOP
    -- Generate customer ID if not exists
    customer_id_var := 'cus_' || substr(md5(user_record.user_id::text), 1, 24);
    
    -- Scenario 1: Successful subscription payment
    payment_id_var := 'pi_' || substr(md5(user_record.user_id::text || '1'), 1, 24);
    amount_var := 3900; -- £39.00
    status_var := 'succeeded';
    subscription_id_var := 'sub_' || substr(md5(user_record.user_id::text || 'sub'), 1, 24);
    
    INSERT INTO payments (
      id,
      user_id,
      stripe_customer_id,
      amount,
      currency,
      status,
      stripe_invoice_id,
      stripe_subscription_id,
      created_at
    )
    VALUES (
      payment_id_var,
      user_record.user_id,
      customer_id_var,
      amount_var,
      'gbp',
      status_var,
      'in_' || substr(md5(payment_id_var), 1, 24),
      subscription_id_var,
      NOW() - INTERVAL '30 days'
    )
    ON CONFLICT (id) DO UPDATE SET
      amount = EXCLUDED.amount,
      status = EXCLUDED.status;
    
    -- Scenario 2: Failed payment
    payment_id_var := 'pi_' || substr(md5(user_record.user_id::text || '2'), 1, 24);
    amount_var := 7900; -- £79.00
    status_var := 'failed';
    
    INSERT INTO payments (
      id,
      user_id,
      stripe_customer_id,
      amount,
      currency,
      status,
      created_at
    )
    VALUES (
      payment_id_var,
      user_record.user_id,
      customer_id_var,
      amount_var,
      'gbp',
      status_var,
      NOW() - INTERVAL '15 days'
    )
    ON CONFLICT (id) DO UPDATE SET
      amount = EXCLUDED.amount,
      status = EXCLUDED.status;
    
    -- Scenario 3: Pending payment
    payment_id_var := 'pi_' || substr(md5(user_record.user_id::text || '3'), 1, 24);
    amount_var := 3900;
    status_var := 'pending';
    
    INSERT INTO payments (
      id,
      user_id,
      stripe_customer_id,
      amount,
      currency,
      status,
      created_at
    )
    VALUES (
      payment_id_var,
      user_record.user_id,
      customer_id_var,
      amount_var,
      'gbp',
      status_var,
      NOW() - INTERVAL '1 day'
    )
    ON CONFLICT (id) DO UPDATE SET
      amount = EXCLUDED.amount,
      status = EXCLUDED.status;
  END LOOP;
END $$;
*/

-- Example 4: Simple seed - Create payments for users with subscriptions
-- Most straightforward approach - creates one payment per active subscription
-- Uncomment and modify when you have users and subscriptions:
/*
INSERT INTO payments (id, user_id, stripe_customer_id, amount, currency, status, stripe_invoice_id, stripe_subscription_id, created_at)
SELECT 
  'pi_' || substr(md5(s.id || s.user_id::text), 1, 24) as id,
  s.user_id,
  s.stripe_customer_id,
  CASE 
    WHEN s.stripe_price_id LIKE '%essential%' THEN 3900
    WHEN s.stripe_price_id LIKE '%pro%' THEN 7900
    ELSE 3900
  END as amount,
  'gbp' as currency,
  'succeeded' as status,
  'in_' || substr(md5(s.id), 1, 24) as stripe_invoice_id,
  s.id as stripe_subscription_id,
  COALESCE(s.current_period_start, s.created_at) as created_at
FROM subscriptions s
WHERE s.status IN ('active', 'trialing')
ON CONFLICT (id) DO UPDATE SET
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  status = EXCLUDED.status,
  stripe_invoice_id = EXCLUDED.stripe_invoice_id,
  stripe_subscription_id = EXCLUDED.stripe_subscription_id;
*/

-- Note: In production, payments are created automatically by Stripe webhooks:
-- 1. User completes payment in Stripe
-- 2. Stripe sends invoice.paid webhook
-- 3. Webhook handler creates/updates payment record
-- 4. Payment ID is Stripe payment_intent ID (pi_...) or charge ID (ch_...)
-- 5. Amount comes from Stripe invoice.total
-- 6. Status is determined by payment outcome

COMMIT;
