-- Seed request_logs: API request logs for debugging and monitoring
-- NOTE: This table is typically auto-generated by the request logger utility
-- This script provides example queries that can be run for testing the admin logs interface
--
-- NOTE: This script should be run using a direct database connection (psql)
-- which bypasses Row Level Security (RLS). The connection string should be
-- the "Direct connection" or "Transaction pooler" from Supabase Dashboard.

BEGIN;

-- Dependencies:
-- - auth.users (optional - for user_id references)
-- - request_logs (no strict dependencies, but user_id references auth.users)

-- IMPORTANT: 
-- - Request logs are immutable (no updates or deletes allowed)
-- - Only admins can read request logs (RLS policy)
-- - System can insert request logs via service role
-- - Used for debugging and monitoring critical endpoints
-- - error_stack and error_message are only populated for errors

-- Example 1: Seed request_logs with realistic API requests
-- Creates realistic request logs for various endpoints and status codes
-- Uncomment and modify when you want to test the admin logs interface:
/*
DO $$
DECLARE
  log_record RECORD;
  request_id_var VARCHAR(255);
  user_id_var UUID;
  path_var VARCHAR(500);
  method_var VARCHAR(10);
  status_var INTEGER;
  duration_var INTEGER;
  error_stack_var TEXT;
  error_message_var TEXT;
  ip_address_var INET;
  user_agent_var TEXT;
  log_counter INTEGER;
  paths TEXT[] := ARRAY[
    '/api/jobs',
    '/api/jobs/123',
    '/api/offers',
    '/api/portfolio/projects',
    '/api/questions',
    '/api/answers',
    '/api/events',
    '/api/admin/logs',
    '/api/stripe/webhook',
    '/api/subscription/status'
  ];
  methods TEXT[] := ARRAY['GET', 'POST', 'PUT', 'DELETE', 'PATCH'];
  user_agents TEXT[] := ARRAY[
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
    'PostmanRuntime/7.32.3',
    'curl/7.88.1'
  ];
BEGIN
  -- Get some users for user_id references (optional)
  SELECT id INTO user_id_var FROM auth.users LIMIT 1;
  
  -- Create 50 request logs
  FOR log_counter IN 1..50 LOOP
    -- Generate request ID (UUID-like format)
    request_id_var := 'req_' || substr(md5(random()::text || log_counter::text), 1, 32);
    
    -- Random path and method
    path_var := paths[1 + FLOOR(RANDOM() * (array_length(paths, 1) - 1))::INTEGER];
    method_var := methods[1 + FLOOR(RANDOM() * (array_length(methods, 1) - 1))::INTEGER];
    
    -- Status code distribution: 70% 2xx, 20% 4xx, 10% 5xx
    IF RANDOM() < 0.7 THEN
      status_var := 200 + FLOOR(RANDOM() * 3)::INTEGER; -- 200-202
    ELSIF RANDOM() < 0.9 THEN
      status_var := 400 + FLOOR(RANDOM() * 4)::INTEGER; -- 400-403
    ELSE
      status_var := 500 + FLOOR(RANDOM() * 2)::INTEGER; -- 500-501
    END IF;
    
    -- Duration: 50-2000ms for successful, 100-5000ms for errors
    IF status_var < 400 THEN
      duration_var := 50 + FLOOR(RANDOM() * 1950)::INTEGER;
    ELSE
      duration_var := 100 + FLOOR(RANDOM() * 4900)::INTEGER;
    END IF;
    
    -- Error information only for 5xx errors
    IF status_var >= 500 THEN
      error_message_var := 'Internal server error: ' || substr(md5(random()::text), 1, 16);
      error_stack_var := 'Error: ' || error_message_var || E'\n    at handler (/app/api/route.ts:123)\n    at processRequest (/app/lib/utils.ts:456)';
    ELSE
      error_message_var := NULL;
      error_stack_var := NULL;
    END IF;
    
    -- 30% have user_id, 70% are anonymous
    IF RANDOM() < 0.3 AND user_id_var IS NOT NULL THEN
      -- Get random user
      SELECT id INTO user_id_var FROM auth.users ORDER BY RANDOM() LIMIT 1;
    ELSE
      user_id_var := NULL;
    END IF;
    
    -- IP address (80% have IP)
    IF RANDOM() < 0.8 THEN
      ip_address_var := ('192.168.' || (1 + FLOOR(RANDOM() * 254)::INTEGER) || '.' || (1 + FLOOR(RANDOM() * 254)::INTEGER))::INET;
    ELSE
      ip_address_var := NULL;
    END IF;
    
    -- User agent (70% have user agent)
    IF RANDOM() < 0.7 THEN
      user_agent_var := user_agents[1 + FLOOR(RANDOM() * (array_length(user_agents, 1) - 1))::INTEGER];
    ELSE
      user_agent_var := NULL;
    END IF;
    
    INSERT INTO request_logs (
      request_id,
      user_id,
      path,
      method,
      status,
      duration,
      error_stack,
      error_message,
      ip_address,
      user_agent,
      created_at
    )
    VALUES (
      request_id_var,
      user_id_var,
      path_var,
      method_var,
      status_var,
      duration_var,
      error_stack_var,
      error_message_var,
      ip_address_var,
      user_agent_var,
      NOW() - INTERVAL '1 hour' * (50 - log_counter)  -- Spread over last 50 hours
    );
  END LOOP;
END $$;
*/

-- Example 2: Seed request_logs with specific error scenarios
-- Creates request logs demonstrating various error conditions
-- Uncomment and modify when you want to test error handling:
/*
DO $$
DECLARE
  error_scenarios RECORD;
  request_id_var VARCHAR(255);
  user_id_var UUID;
BEGIN
  -- Get a user for user_id references
  SELECT id INTO user_id_var FROM auth.users LIMIT 1;
  
  -- Scenario 1: 500 error on /api/jobs
  request_id_var := 'req_error_001';
  INSERT INTO request_logs (
    request_id,
    user_id,
    path,
    method,
    status,
    duration,
    error_stack,
    error_message,
    ip_address,
    user_agent,
    created_at
  )
  VALUES (
    request_id_var,
    user_id_var,
    '/api/jobs',
    'GET',
    500,
    2500,
    'Error: Database connection timeout' || E'\n    at queryJobs (/app/api/jobs/route.ts:45)\n    at GET (/app/api/jobs/route.ts:123)',
    'Database connection timeout',
    '192.168.1.100'::INET,
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    NOW() - INTERVAL '2 hours'
  );
  
  -- Scenario 2: 401 error on /api/admin/logs (unauthorized)
  request_id_var := 'req_error_002';
  INSERT INTO request_logs (
    request_id,
    user_id,
    path,
    method,
    status,
    duration,
    error_message,
    ip_address,
    user_agent,
    created_at
  )
  VALUES (
    request_id_var,
    NULL,
    '/api/admin/logs',
    'GET',
    401,
    150,
    'Unauthorized: Admin role required',
    '192.168.1.101'::INET,
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    NOW() - INTERVAL '1 hour'
  );
  
  -- Scenario 3: 404 error on /api/jobs/999
  request_id_var := 'req_error_003';
  INSERT INTO request_logs (
    request_id,
    user_id,
    path,
    method,
    status,
    duration,
    error_message,
    ip_address,
    user_agent,
    created_at
  )
  VALUES (
    request_id_var,
    user_id_var,
    '/api/jobs/999',
    'GET',
    404,
    200,
    'Job not found',
    '192.168.1.102'::INET,
    'PostmanRuntime/7.32.3',
    NOW() - INTERVAL '30 minutes'
  );
  
  -- Scenario 4: 200 success on /api/jobs
  request_id_var := 'req_success_001';
  INSERT INTO request_logs (
    request_id,
    user_id,
    path,
    method,
    status,
    duration,
    ip_address,
    user_agent,
    created_at
  )
  VALUES (
    request_id_var,
    user_id_var,
    '/api/jobs',
    'GET',
    200,
    350,
    '192.168.1.103'::INET,
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    NOW() - INTERVAL '15 minutes'
  );
END $$;
*/

-- Example 3: Seed request_logs with recent activity
-- Creates request logs for the last 24 hours
-- Uncomment and modify when you want to test recent activity:
/*
DO $$
DECLARE
  log_counter INTEGER;
  request_id_var VARCHAR(255);
  user_id_var UUID;
  path_var VARCHAR(500);
  method_var VARCHAR(10);
  status_var INTEGER;
  duration_var INTEGER;
  paths TEXT[] := ARRAY[
    '/api/jobs',
    '/api/offers',
    '/api/portfolio/projects',
    '/api/questions',
    '/api/events'
  ];
BEGIN
  -- Get a user for user_id references
  SELECT id INTO user_id_var FROM auth.users LIMIT 1;
  
  -- Create 100 request logs over the last 24 hours
  FOR log_counter IN 1..100 LOOP
    request_id_var := 'req_' || substr(md5(random()::text || log_counter::text), 1, 32);
    path_var := paths[1 + FLOOR(RANDOM() * (array_length(paths, 1) - 1))::INTEGER];
    method_var := 'GET';
    
    -- 90% success, 10% errors
    IF RANDOM() < 0.9 THEN
      status_var := 200;
      duration_var := 100 + FLOOR(RANDOM() * 900)::INTEGER;
    ELSE
      status_var := 500;
      duration_var := 1000 + FLOOR(RANDOM() * 2000)::INTEGER;
    END IF;
    
    INSERT INTO request_logs (
      request_id,
      user_id,
      path,
      method,
      status,
      duration,
      error_message,
      ip_address,
      user_agent,
      created_at
    )
    VALUES (
      request_id_var,
      CASE WHEN RANDOM() < 0.5 THEN user_id_var ELSE NULL END,
      path_var,
      method_var,
      status_var,
      duration_var,
      CASE WHEN status_var >= 500 THEN 'Internal server error' ELSE NULL END,
      ('192.168.' || (1 + FLOOR(RANDOM() * 254)::INTEGER) || '.' || (1 + FLOOR(RANDOM() * 254)::INTEGER))::INET,
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
      NOW() - INTERVAL '1 hour' * (RANDOM() * 24)
    );
  END LOOP;
END $$;
*/

-- Example 4: Simple seed - Create request logs for common endpoints
-- Most straightforward approach - creates logs for common API endpoints
-- Uncomment and modify when you want to test the admin logs interface:
/*
INSERT INTO request_logs (
  request_id,
  user_id,
  path,
  method,
  status,
  duration,
  ip_address,
  user_agent,
  created_at
)
SELECT 
  'req_' || substr(md5(random()::text || row_number() OVER ()::text), 1, 32) as request_id,
  CASE WHEN RANDOM() < 0.3 THEN (SELECT id FROM auth.users ORDER BY RANDOM() LIMIT 1) ELSE NULL END as user_id,
  unnest(ARRAY['/api/jobs', '/api/offers', '/api/portfolio/projects', '/api/questions', '/api/events']) as path,
  'GET' as method,
  CASE 
    WHEN RANDOM() < 0.8 THEN 200
    WHEN RANDOM() < 0.95 THEN 400 + FLOOR(RANDOM() * 4)::INTEGER
    ELSE 500 + FLOOR(RANDOM() * 2)::INTEGER
  END as status,
  100 + FLOOR(RANDOM() * 1900)::INTEGER as duration,
  ('192.168.' || (1 + FLOOR(RANDOM() * 254)::INTEGER) || '.' || (1 + FLOOR(RANDOM() * 254)::INTEGER))::INET as ip_address,
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36' as user_agent,
  NOW() - INTERVAL '1 hour' * FLOOR(RANDOM() * 48)::INTEGER as created_at
FROM generate_series(1, 50);
*/

-- Note: In production, request_logs are created automatically:
-- 1. API request is made to a critical endpoint
-- 2. Request logger utility logs the request
-- 3. Request log is inserted into request_logs table
-- 4. Only admins can read request logs (RLS policy)
-- 5. Request logs are immutable (no updates or deletes)
--
-- This seed file is useful for:
-- - Testing the admin logs interface
-- - Demonstrating error scenarios
-- - Testing log filtering and pagination
-- - Creating realistic test data for monitoring dashboards

COMMIT;
