-- Create resumes bucket for storing user CV/Resume files
-- Based on SUPABASE_RESUMES_BUCKET_SETUP.md documentation

-- ============================================
-- Create resumes bucket
-- ============================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'resumes',
  'resumes',
  false, -- private bucket (CVs are sensitive documents)
  10485760, -- 10MB limit
  ARRAY[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ============================================
-- Storage Policies for resumes bucket
-- ============================================
-- 
-- IMPORTANT: These policies are STUDENT-ONLY.
-- Recruiters do NOT have direct storage access via RLS policies.
-- Recruiters access CVs through server-signed URLs generated by:
--   GET /api/recruiter/cv/signed-url
-- This endpoint validates access grants and generates time-limited signed URLs.
-- This design is more secure and provides better audit control.

-- INSERT: Users can upload only to their own user-scoped paths
-- Path format: userId/resume-timestamp.ext
DROP POLICY IF EXISTS "Users can upload their own CVs" ON storage.objects;
DO $$
BEGIN
  EXECUTE 'CREATE POLICY "Users can upload their own CVs"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (
      bucket_id = ''resumes'' AND
      (storage.foldername(name))[1] = auth.uid()::text
    )';
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

-- SELECT: Users can read their own CVs
DROP POLICY IF EXISTS "Users can read their own CVs" ON storage.objects;
DO $$
BEGIN
  EXECUTE 'CREATE POLICY "Users can read their own CVs"
    ON storage.objects
    FOR SELECT
    TO authenticated
    USING (
      bucket_id = ''resumes'' AND
      (storage.foldername(name))[1] = auth.uid()::text
    )';
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

-- DELETE: Users can delete their own CVs
DROP POLICY IF EXISTS "Users can delete their own CVs" ON storage.objects;
DO $$
BEGIN
  EXECUTE 'CREATE POLICY "Users can delete their own CVs"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (
      bucket_id = ''resumes'' AND
      (storage.foldername(name))[1] = auth.uid()::text
    )';
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;
