#!/usr/bin/env tsx
/**
 * Diagnostic script to help investigate errors by Next.js error digest
 * 
 * Usage:
 *   tsx scripts/diagnose-error-digest.ts 1210891470
 * 
 * Or set ERROR_DIGEST environment variable:
 *   ERROR_DIGEST=1210891470 tsx scripts/diagnose-error-digest.ts
 * 
 * Note: Next.js error digests are hashes, not directly queryable.
 * This script helps by:
 * 1. Checking recent error logs in request_logs
 * 2. Checking server logs for similar error patterns
 * 3. Providing guidance on how to investigate
 */

import { createServerSupabaseClient } from '../lib/supabase/server';

const ERROR_DIGEST = process.argv[2] || process.env.ERROR_DIGEST;

if (!ERROR_DIGEST) {
  console.error('❌ Error: Error digest required');
  console.error('Usage: tsx scripts/diagnose-error-digest.ts <error-digest>');
  console.error('   Or: ERROR_DIGEST=<error-digest> tsx scripts/diagnose-error-digest.ts');
  process.exit(1);
}

async function diagnoseErrorDigest() {
  console.log(`\n🔍 Diagnosing Error Digest: ${ERROR_DIGEST}\n`);
  console.log('='.repeat(80));

  const supabase = createServerSupabaseClient();

  console.log('\n📋 Note: Next.js error digests are hashes generated by the error boundary.');
  console.log('   They are not directly stored in the database, but errors are logged.');
  console.log('   Checking recent error logs that might be related...\n');

  // 1. Check recent error logs (500 status codes) from portfolio-related endpoints
  console.log('📋 1. Recent Error Logs (Portfolio-related endpoints)');
  console.log('-'.repeat(80));
  
  const { data: errorLogs, error: logsError } = await supabase
    .from('request_logs')
    .select('*')
    .in('path', ['/api/portfolio/profile', '/student/portfolio'])
    .eq('status', 500)
    .order('created_at', { ascending: false })
    .limit(20);

  if (logsError) {
    console.error('❌ Error querying request_logs:', logsError);
  } else if (!errorLogs || errorLogs.length === 0) {
    console.log('⚠️  No recent error logs found for portfolio endpoints');
    console.log('   This could mean:');
    console.log('   - Error occurred before request_logs table was created');
    console.log('   - Error occurred during server-side rendering (not an API call)');
    console.log('   - Error was caught by error boundary before logging');
  } else {
    console.log(`\n   Found ${errorLogs.length} recent error(s):\n`);
    errorLogs.forEach((log, idx) => {
      console.log(`   Error ${idx + 1}:`);
      console.log(`   - Request ID: ${log.request_id}`);
      console.log(`   - Path: ${log.path}`);
      console.log(`   - Method: ${log.method}`);
      console.log(`   - Status: ${log.status}`);
      console.log(`   - Duration: ${log.duration}ms`);
      console.log(`   - User ID: ${log.user_id || 'N/A'}`);
      console.log(`   - Created At: ${new Date(log.created_at).toISOString()}`);
      if (log.error_message) {
        console.log(`   - Error Message: ${log.error_message.substring(0, 200)}${log.error_message.length > 200 ? '...' : ''}`);
      }
      if (log.error_stack) {
        const stackPreview = log.error_stack.substring(0, 300);
        console.log(`   - Error Stack (preview):`);
        console.log(`     ${stackPreview.split('\n').slice(0, 5).join('\n     ')}${log.error_stack.length > 300 ? '...' : ''}`);
      }
      console.log('');
    });
  }

  // 2. Check for common error patterns
  console.log('\n\n📋 2. Common Error Patterns to Check');
  console.log('-'.repeat(80));
  console.log(`
   Common causes of portfolio page errors:
   
   1. Database Connection Issues
      - Check Supabase connection
      - Verify environment variables (NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY)
   
   2. Authentication Errors
      - User session expired
      - Invalid auth token
      - Check: supabase.auth.getUser() calls
   
   3. Database Query Errors
      - Missing profile or student_profile
      - RLS (Row Level Security) policy blocking access
      - Check: .single() calls that might fail if no rows found
   
   4. Data Serialization Issues
      - Invalid date formats
      - Circular references in data
      - Check: safeDateSerialize() function usage
   
   5. Missing Dependencies
      - Required environment variables not set
      - Missing database tables or columns
   
   To investigate further:
   1. Check server logs (Vercel logs, local console)
   2. Look for error messages containing: "${ERROR_DIGEST.substring(0, 8)}"
   3. Check browser console for client-side errors
   4. Review recent deployments or code changes
   5. Check database for missing data (profiles, student_profiles)
  `);

  // 3. Provide SQL query to check for data issues
  console.log('\n\n📋 3. SQL Queries to Check Data Integrity');
  console.log('-'.repeat(80));
  console.log(`
   Run these queries in Supabase SQL editor to check for data issues:
   
   -- Check for users without profiles
   SELECT u.id, u.email, u.created_at
   FROM auth.users u
   LEFT JOIN profiles p ON p.user_id = u.id
   WHERE p.id IS NULL;
   
   -- Check for profiles without student_profiles
   SELECT p.id, p.user_id, p.role, p.created_at
   FROM profiles p
   LEFT JOIN student_profiles sp ON sp.profile_id = p.id
   WHERE p.role = 'student' AND sp.id IS NULL;
   
   -- Check for orphaned portfolio projects
   SELECT pp.id, pp.student_profile_id, pp.title
   FROM portfolio_projects pp
   LEFT JOIN student_profiles sp ON sp.id = pp.student_profile_id
   WHERE sp.id IS NULL;
  `);

  console.log('\n\n✅ Diagnosis complete. Use the information above to investigate the error.');
  console.log(`   Error Digest: ${ERROR_DIGEST}`);
  console.log('   If this error persists, check server logs and database integrity.\n');
}

diagnoseErrorDigest().catch((error) => {
  console.error('❌ Error running diagnosis:', error);
  process.exit(1);
});
