'use client';

import { useState } from 'react';
import { logToolRunSafe } from '@/lib/tools/logToolRun';

interface GTMSystemDesignerClientProps {
  toolId: string;
  studentProfileId: string;
}

/**
 * Example tool client component showing how to integrate logToolRun
 * 
 * When a tool is submitted/executed, call logToolRunSafe() with:
 * - toolId: The tool identifier from registry
 * - studentProfileId: The current student's profile ID
 * - inputs: The parameters/inputs provided by the user
 * - outputs: The results/artifacts generated by the tool
 */
export function GTMSystemDesignerClient({ 
  toolId, 
  studentProfileId 
}: GTMSystemDesignerClientProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);

    // Example: Collect form inputs
    const formData = new FormData(e.currentTarget);
    const inputs = {
      targetAudience: formData.get('targetAudience') as string,
      budget: formData.get('budget') as string,
      timeline: formData.get('timeline') as string,
    };

    try {
      // TODO: Execute tool logic here
      // For now, simulate tool execution
      const outputs = {
        systemMap: 'Generated system map...',
        recommendations: ['Recommendation 1', 'Recommendation 2'],
        artifacts: [
          {
            type: 'diagram',
            title: 'GTM System Architecture',
            url: '#',
          },
        ],
      };

      // Log the tool run (non-blocking)
      await logToolRunSafe({
        toolId,
        studentProfileId,
        inputs,
        outputs,
      });

      // TODO: Show success message or redirect
      alert('Tool executed successfully! Check console for logged run.');
    } catch (error) {
      console.error('Tool execution failed:', error);
      alert('Tool execution failed. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6">
      <h2 className="text-xl font-semibold text-gray-900 mb-4">What this tool does</h2>
      <p className="text-gray-600 mb-6">
        The GTM System Designer helps you design and architect go-to-market systems with AI-native approaches. 
        Build scalable GTM strategies and workflows that align with your business objectives.
      </p>

      {/* Example Form - shows integration pattern */}
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label htmlFor="targetAudience" className="block text-sm font-medium text-gray-700 mb-1">
            Target Audience
          </label>
          <input
            type="text"
            id="targetAudience"
            name="targetAudience"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand-light focus:border-brand-light"
            placeholder="e.g., B2B SaaS companies"
            required
          />
        </div>

        <div>
          <label htmlFor="budget" className="block text-sm font-medium text-gray-700 mb-1">
            Budget
          </label>
          <input
            type="text"
            id="budget"
            name="budget"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand-light focus:border-brand-light"
            placeholder="e.g., $50,000"
            required
          />
        </div>

        <div>
          <label htmlFor="timeline" className="block text-sm font-medium text-gray-700 mb-1">
            Timeline
          </label>
          <input
            type="text"
            id="timeline"
            name="timeline"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand-light focus:border-brand-light"
            placeholder="e.g., 6 months"
            required
          />
        </div>

        <button
          type="submit"
          disabled={isSubmitting}
          className="w-full px-4 py-2.5 bg-brand-light text-white text-sm font-medium rounded-lg hover:bg-brand-light/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? 'Processing...' : 'Generate GTM System'}
        </button>
      </form>

      <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
        <p className="text-sm text-gray-600">
          <strong>Status:</strong> Coming Soon
        </p>
        <p className="text-sm text-gray-500 mt-2">
          This tool is currently under development. The form above demonstrates how tool runs are logged.
          Check the browser console to see logged tool runs.
        </p>
      </div>
    </div>
  );
}
